import { useState } from "react";
import { supabase } from './supabase';
const T={cream:"#E8E0D0",cream2:"#DDD4C0",ivory:"#F0EAD8",brown:"#1A0E08",brown2:"#3D2418",brown3:"#6B4535",beige:"#B8955F",gold:"#8A6A38",goldL:"rgba(138,106,56,.15)",line:"rgba(26,14,8,.15)",lineL:"rgba(26,14,8,.1)",green:"#4A7A42",greenL:"rgba(74,122,66,.1)",red:"#8B3A3A",redL:"rgba(139,58,58,.08)",blue:"#3A5A8B",blueL:"rgba(58,90,139,.08)",orange:"#8B6A3A"};

const css=`
@import url('https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,200;0,300;0,400;0,500;1,200;1,300;1,400&family=Montserrat:wght@300;400;500;600&display=swap');
*,*::before,*::after{margin:0;padding:0;box-sizing:border-box;}
html,body{overflow-x:hidden;max-width:100vw;}
body{background:${T.cream};color:${T.brown};font-family:'Montserrat',sans-serif;font-weight:400;-webkit-font-smoothing:antialiased;}
::-webkit-scrollbar{width:3px;}::-webkit-scrollbar-thumb{background:${T.gold};}
input,select,textarea{width:100%;background:transparent;border:none;border-bottom:1px solid ${T.brown};color:${T.brown};font-family:'Montserrat',sans-serif;font-size:.72rem;padding:.6rem 0;outline:none;-webkit-appearance:none;border-radius:0;}
input:focus,select:focus,textarea:focus{border-bottom-color:${T.gold};}
input::placeholder,textarea::placeholder{color:rgba(26,14,8,.35);}
select option{background:${T.ivory};color:${T.brown};}
label{font-size:.5rem;letter-spacing:.22em;text-transform:uppercase;color:${T.brown3};display:block;margin-bottom:.5rem;}
table{width:100%;border-collapse:collapse;}
th{font-size:.46rem;letter-spacing:.18em;text-transform:uppercase;color:${T.brown3};padding:.8rem 1.2rem;text-align:left;border-bottom:1px solid ${T.line};}
td{font-size:.62rem;padding:.85rem 1.2rem;border-bottom:1px solid ${T.lineL};color:${T.brown2};vertical-align:middle;}
tr:last-child td{border:none;}
@keyframes fadeUp{from{opacity:0;transform:translateY(16px);}to{opacity:1;transform:translateY(0);}}
`;

const useW=()=>{const[w,setW]=useState(typeof window!=="undefined"?window.innerWidth:800);if(typeof window!=="undefined")window.onresize=()=>setW(window.innerWidth);return w;};

// ── HEROICONS B ────────────────────────────────────────────
const I={
  Home:()=><svg width="16" height="16" fill="none" stroke="currentColor" strokeWidth="1.5" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" d="M2.25 12l8.954-8.955c.44-.439 1.152-.439 1.591 0L21.75 12M4.5 9.75v10.125c0 .621.504 1.125 1.125 1.125H9.75v-4.875c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21h4.125c.621 0 1.125-.504 1.125-1.125V9.75M8.25 21h8.25"/></svg>,
  Users:()=><svg width="16" height="16" fill="none" stroke="currentColor" strokeWidth="1.5" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" d="M15 19.128a9.38 9.38 0 002.625.372 9.337 9.337 0 004.121-.952 4.125 4.125 0 00-7.533-2.493M15 19.128v-.003c0-1.113-.285-2.16-.786-3.07M15 19.128v.106A12.318 12.318 0 018.624 21c-2.331 0-4.512-.645-6.374-1.766l-.001-.109a6.375 6.375 0 0111.964-3.07M12 6.375a3.375 3.375 0 11-6.75 0 3.375 3.375 0 016.75 0zm8.25 2.25a2.625 2.625 0 11-5.25 0 2.625 2.625 0 015.25 0z"/></svg>,
  Doc:()=><svg width="16" height="16" fill="none" stroke="currentColor" strokeWidth="1.5" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" d="M19.5 14.25v-2.625a3.375 3.375 0 00-3.375-3.375h-1.5A1.125 1.125 0 0113.5 7.125v-1.5a3.375 3.375 0 00-3.375-3.375H8.25m0 12.75h7.5m-7.5 3H12M10.5 2.25H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 00-9-9z"/></svg>,
  Chart:()=><svg width="16" height="16" fill="none" stroke="currentColor" strokeWidth="1.5" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" d="M3 13.125C3 12.504 3.504 12 4.125 12h2.25c.621 0 1.125.504 1.125 1.125v6.75C7.5 20.496 6.996 21 6.375 21h-2.25A1.125 1.125 0 013 19.875v-6.75zM9.75 8.625c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125v11.25c0 .621-.504 1.125-1.125 1.125h-2.25a1.125 1.125 0 01-1.125-1.125V8.625zM16.5 4.125c0-.621.504-1.125 1.125-1.125h2.25C20.496 3 21 3.504 21 4.125v15.75c0 .621-.504 1.125-1.125 1.125h-2.25a1.125 1.125 0 01-1.125-1.125V4.125z"/></svg>,
  Bell:()=><svg width="16" height="16" fill="none" stroke="currentColor" strokeWidth="1.5" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" d="M14.857 17.082a23.848 23.848 0 005.454-1.31A8.967 8.967 0 0118 9.75v-.7V9A6 6 0 006 9v.75a8.967 8.967 0 01-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 01-5.714 0m5.714 0a3 3 0 11-5.714 0"/></svg>,
  Gear:()=><svg width="16" height="16" fill="none" stroke="currentColor" strokeWidth="1.5" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" d="M9.594 3.94c.09-.542.56-.94 1.11-.94h2.593c.55 0 1.02.398 1.11.94l.213 1.281c.063.374.313.686.645.87.074.04.147.083.22.127.324.196.72.257 1.075.124l1.217-.456a1.125 1.125 0 011.37.49l1.296 2.247a1.125 1.125 0 01-.26 1.431l-1.003.827c-.293.24-.438.613-.431.992a6.759 6.759 0 010 .255c-.007.378.138.75.43.99l1.005.828c.424.35.534.954.26 1.43l-1.298 2.247a1.125 1.125 0 01-1.369.491l-1.217-.456c-.355-.133-.75-.072-1.076.124a6.57 6.57 0 01-.22.128c-.331.183-.581.495-.644.869l-.213 1.28c-.09.543-.56.941-1.11.941h-2.594c-.55 0-1.02-.398-1.11-.94l-.213-1.281c-.062-.374-.312-.686-.644-.87a6.52 6.52 0 01-.22-.127c-.325-.196-.72-.257-1.076-.124l-1.217.456a1.125 1.125 0 01-1.369-.49l-1.297-2.247a1.125 1.125 0 01.26-1.431l1.004-.827c.292-.24.437-.613.43-.992a6.932 6.932 0 010-.255c.007-.378-.138-.75-.43-.99l-1.004-.828a1.125 1.125 0 01-.26-1.43l1.297-2.247a1.125 1.125 0 011.37-.491l1.216.456c.356.133.751.072 1.076-.124.072-.044.146-.087.22-.128.332-.183.582-.495.644-.869l.214-1.281z"/><path strokeLinecap="round" strokeLinejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"/></svg>,
  Building:()=><svg width="16" height="16" fill="none" stroke="currentColor" strokeWidth="1.5" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" d="M3.75 21h16.5M4.5 3h15M5.25 3v18m13.5-18v18M9 6.75h1.5m-1.5 3h1.5m-1.5 3h1.5m3-6H15m-1.5 3H15m-1.5 3H15M9 21v-3.375c0-.621.504-1.125 1.125-1.125h3.75c.621 0 1.125.504 1.125 1.125V21"/></svg>,
  Star:()=><svg width="16" height="16" fill="none" stroke="currentColor" strokeWidth="1.5" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" d="M11.48 3.499a.562.562 0 011.04 0l2.125 5.111a.563.563 0 00.475.345l5.518.442c.499.04.701.663.321.988l-4.204 3.602a.563.563 0 00-.182.557l1.285 5.385a.562.562 0 01-.84.61l-4.725-2.885a.563.563 0 00-.586 0L6.982 20.54a.562.562 0 01-.84-.61l1.285-5.386a.562.562 0 00-.182-.557l-4.204-3.602a.563.563 0 01.321-.988l5.518-.442a.563.563 0 00.475-.345L11.48 3.5z"/></svg>,
  Shield:()=><svg width="16" height="16" fill="none" stroke="currentColor" strokeWidth="1.5" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" d="M9 12.75L11.25 15 15 9.75m-3-7.036A11.959 11.959 0 013.598 6 11.99 11.99 0 003 9.749c0 5.592 3.824 10.29 9 11.623 5.176-1.332 9-6.03 9-11.622 0-1.31-.21-2.571-.598-3.751h-.152c-3.196 0-6.1-1.248-8.25-3.285z"/></svg>,
  Calendar:()=><svg width="16" height="16" fill="none" stroke="currentColor" strokeWidth="1.5" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" d="M6.75 3v2.25M17.25 3v2.25M3 18.75V7.5a2.25 2.25 0 012.25-2.25h13.5A2.25 2.25 0 0121 7.5v11.25m-18 0A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75m-18 0v-7.5A2.25 2.25 0 015.25 9h13.5A2.25 2.25 0 0121 11.25v7.5"/></svg>,
  Message:()=><svg width="16" height="16" fill="none" stroke="currentColor" strokeWidth="1.5" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" d="M2.25 12.76c0 1.6 1.123 2.994 2.707 3.227 1.087.16 2.185.283 3.293.369V21l4.076-4.076a1.526 1.526 0 011.037-.443 48.282 48.282 0 005.68-.494c1.584-.233 2.707-1.626 2.707-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0012 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018z"/></svg>,
  Money:()=><svg width="16" height="16" fill="none" stroke="currentColor" strokeWidth="1.5" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" d="M2.25 18.75a60.07 60.07 0 0115.797 2.101c.727.198 1.453-.342 1.453-1.096V18.75M3.75 4.5v.75A.75.75 0 013 6h-.75m0 0v-.375c0-.621.504-1.125 1.125-1.125H20.25M2.25 6v9m18-10.5v.75c0 .414.336.75.75.75h.75m-1.5-1.5h.375c.621 0 1.125.504 1.125 1.125v9.75c0 .621-.504 1.125-1.125 1.125h-.375m1.5-1.5H21a.75.75 0 00-.75.75v.75m0 0H3.75m0 0h-.375a1.125 1.125 0 01-1.125-1.125V15m1.5 1.5v-.75A.75.75 0 003 15h-.75"/></svg>,
  Person:()=><svg width="16" height="16" fill="none" stroke="currentColor" strokeWidth="1.5" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" d="M15.75 6a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0zM4.501 20.118a7.5 7.5 0 0114.998 0A17.933 17.933 0 0112 21.75c-2.676 0-5.216-.584-7.499-1.632z"/></svg>,
  Plus:()=><svg width="16" height="16" fill="none" stroke="currentColor" strokeWidth="1.5" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" d="M12 4.5v15m7.5-7.5h-15"/></svg>,
  Warning:()=><svg width="16" height="16" fill="none" stroke="currentColor" strokeWidth="1.5" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126zM12 15.75h.007v.008H12v-.008z"/></svg>,
  Eye:()=><svg width="16" height="16" fill="none" stroke="currentColor" strokeWidth="1.5" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" d="M2.036 12.322a1.012 1.012 0 010-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.641 0-8.573-3.007-9.964-7.178z"/><path strokeLinecap="round" strokeLinejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"/></svg>,
  Download:()=><svg width="16" height="16" fill="none" stroke="currentColor" strokeWidth="1.5" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5M16.5 12L12 16.5m0 0L7.5 12m4.5 4.5V3"/></svg>,
  Check:()=><svg width="16" height="16" fill="none" stroke="currentColor" strokeWidth="1.5" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" d="M4.5 12.75l6 6 9-13.5"/></svg>,
  Key:()=><svg width="16" height="16" fill="none" stroke="currentColor" strokeWidth="1.5" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" d="M15.75 5.25a3 3 0 013 3m3 0a6 6 0 01-7.029 5.912c-.563-.097-1.159.026-1.563.43L10.5 17.25H8.25v2.25H6v2.25H2.25v-2.818c0-.597.237-1.17.659-1.591l6.499-6.499c.404-.404.527-1 .43-1.563A6 6 0 1121.75 8.25z"/></svg>,
  Handshake:()=><svg width="16" height="16" fill="none" stroke="currentColor" strokeWidth="1.5" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" d="M15.59 14.37a6 6 0 01-5.84 7.38v-4.8m5.84-2.58a14.98 14.98 0 006.16-12.12A14.98 14.98 0 009.631 8.41m5.96 5.96a14.926 14.926 0 01-5.841 2.58m-.119-8.54a6 6 0 00-7.381 5.84h4.8m2.581-5.84a14.927 14.927 0 00-2.58 5.84m2.699 2.7c-.103.021-.207.041-.311.06a15.09 15.09 0 01-2.448-2.448 14.9 14.9 0 01.06-.312m-2.24 2.39a4.493 4.493 0 00-1.757 4.306 4.493 4.493 0 004.306-1.758M16.5 9a1.5 1.5 0 11-3 0 1.5 1.5 0 013 0z"/></svg>,
  Map:()=><svg width="16" height="16" fill="none" stroke="currentColor" strokeWidth="1.5" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" d="M9 6.75V15m6-6v8.25m.503 3.498l4.875-2.437c.381-.19.622-.58.622-1.006V4.82c0-.836-.88-1.38-1.628-1.006l-3.869 1.934c-.317.159-.69.159-1.006 0L9.503 3.252a1.125 1.125 0 00-1.006 0L3.622 5.689C3.24 5.88 3 6.27 3 6.695V19.18c0 .836.88 1.38 1.628 1.006l3.869-1.934c.317-.159.69-.159 1.006 0l4.994 2.497c.317.158.69.158 1.006 0z"/></svg>,
  Academic:()=><svg width="16" height="16" fill="none" stroke="currentColor" strokeWidth="1.5" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" d="M4.26 10.147a60.436 60.436 0 00-.491 6.347A48.627 48.627 0 0112 20.904a48.627 48.627 0 018.232-4.41 60.46 60.46 0 00-.491-6.347m-15.482 0a50.57 50.57 0 00-2.658-.813A59.905 59.905 0 0112 3.493a59.902 59.902 0 0110.399 5.84c-.896.248-1.783.52-2.658.814m-15.482 0A50.697 50.697 0 0112 13.489a50.702 50.702 0 017.74-3.342M6.75 15a.75.75 0 100-1.5.75.75 0 000 1.5zm0 0v-3.675A55.378 55.378 0 0112 8.443m-7.007 11.55A5.981 5.981 0 006.75 15.75v-1.5"/></svg>,
  Book:()=><svg width="16" height="16" fill="none" stroke="currentColor" strokeWidth="1.5" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" d="M12 6.042A8.967 8.967 0 006 3.75c-1.052 0-2.062.18-3 .512v14.25A8.987 8.987 0 016 18c2.305 0 4.408.867 6 2.292m0-14.25a8.966 8.966 0 016-2.292c1.052 0 2.062.18 3 .512v14.25A8.987 8.987 0 0018 18a8.967 8.967 0 00-6 2.292m0-14.25v14.25"/></svg>,
  Inbox:()=><svg width="16" height="16" fill="none" stroke="currentColor" strokeWidth="1.5" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" d="M2.25 13.5h3.86a2.25 2.25 0 012.012 1.244l.256.512a2.25 2.25 0 002.013 1.244h3.218a2.25 2.25 0 002.013-1.244l.256-.512a2.25 2.25 0 012.013-1.244h3.859m-19.5.338V18a2.25 2.25 0 002.25 2.25h15A2.25 2.25 0 0021.75 18v-4.162c0-.224-.034-.447-.1-.661L19.24 5.338a2.25 2.25 0 00-2.15-1.588H6.911a2.25 2.25 0 00-2.15 1.588L2.35 13.177a2.25 2.25 0 00-.1.661z"/></svg>,
  Trend:()=><svg width="16" height="16" fill="none" stroke="currentColor" strokeWidth="1.5" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" d="M2.25 18L9 11.25l4.306 4.307a11.95 11.95 0 015.814-5.519l2.74-1.22m0 0l-5.94-2.28m5.94 2.28l-2.28 5.941"/></svg>,
  Globe:()=><svg width="16" height="16" fill="none" stroke="currentColor" strokeWidth="1.5" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" d="M12 21a9.004 9.004 0 008.716-6.747M12 21a9.004 9.004 0 01-8.716-6.747M12 21c2.485 0 4.5-4.03 4.5-9S14.485 3 12 3m0 18c-2.485 0-4.5-4.03-4.5-9S9.515 3 12 3m0 0a8.997 8.997 0 017.843 4.582M12 3a8.997 8.997 0 00-7.843 4.582m15.686 0A11.953 11.953 0 0112 10.5c-2.998 0-5.74-1.1-7.843-2.918m15.686 0A8.959 8.959 0 0121 12c0 .778-.099 1.533-.284 2.253m0 0A17.919 17.919 0 0112 16.5c-3.162 0-6.133-.815-8.716-2.247m0 0A9.015 9.015 0 013 12c0-1.605.42-3.113 1.157-4.418"/></svg>,
  Lock:()=><svg width="16" height="16" fill="none" stroke="currentColor" strokeWidth="1.5" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" d="M16.5 10.5V6.75a4.5 4.5 0 10-9 0v3.75m-.75 11.25h10.5a2.25 2.25 0 002.25-2.25v-6.75a2.25 2.25 0 00-2.25-2.25H6.75a2.25 2.25 0 00-2.25 2.25v6.75a2.25 2.25 0 002.25 2.25z"/></svg>,
  Camera:()=><svg width="16" height="16" fill="none" stroke="currentColor" strokeWidth="1.5" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" d="M6.827 6.175A2.31 2.31 0 015.186 7.23c-.38.054-.757.112-1.134.175C2.999 7.58 2.25 8.507 2.25 9.574V18a2.25 2.25 0 002.25 2.25h15A2.25 2.25 0 0021.75 18V9.574c0-1.067-.75-1.994-1.802-2.169a47.865 47.865 0 00-1.134-.175 2.31 2.31 0 01-1.64-1.055l-.822-1.316a2.192 2.192 0 00-1.736-1.039 48.774 48.774 0 00-5.232 0 2.192 2.192 0 00-1.736 1.039l-.821 1.316z"/><path strokeLinecap="round" strokeLinejoin="round" d="M16.5 12.75a4.5 4.5 0 11-9 0 4.5 4.5 0 019 0zM18.75 10.5h.008v.008h-.008V10.5z"/></svg>,
  Scale:()=><svg width="16" height="16" fill="none" stroke="currentColor" strokeWidth="1.5" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" d="M12 3v17.25m0 0c-1.472 0-2.882.265-4.185.75M12 20.25c1.472 0 2.882.265 4.185.75M18.75 4.97A48.416 48.416 0 0012 4.5c-2.291 0-4.545.16-6.75.47m13.5 0c1.01.143 2.01.317 3 .52m-3-.52l2.62 10.726c.122.499-.106 1.028-.589 1.202a5.988 5.988 0 01-2.031.352 5.988 5.988 0 01-2.031-.352c-.483-.174-.711-.703-.59-1.202L18.75 4.97zm-16.5.52c.99-.203 1.99-.377 3-.52m0 0l2.62 10.726c.122.499-.106 1.028-.589 1.202a5.989 5.989 0 01-2.031.352 5.989 5.989 0 01-2.031-.352c-.483-.174-.711-.703-.59-1.202L5.25 4.97z"/></svg>,
};

// ── PRIMITIVES ────────────────────────────────────────────
const Tag=({c="beige",children})=>{const m={gold:{color:T.gold,border:"rgba(138,106,56,.35)",bg:T.goldL},green:{color:T.green,border:"rgba(74,122,66,.3)",bg:T.greenL},red:{color:T.red,border:"rgba(139,58,58,.3)",bg:T.redL},blue:{color:T.blue,border:"rgba(58,90,139,.3)",bg:T.blueL},beige:{color:T.brown2,border:"rgba(184,149,95,.4)",bg:"rgba(184,149,95,.1)"},silver:{color:T.brown3,border:T.lineL,bg:"transparent"},orange:{color:T.orange,border:"rgba(139,106,58,.35)",bg:"rgba(139,106,58,.08)"},vip:{color:"#C8952A",border:"rgba(200,149,42,.4)",bg:"rgba(200,149,42,.08)"}};const s=m[c]||m.beige;return <span style={{display:"inline-block",fontSize:".46rem",letterSpacing:".18em",textTransform:"uppercase",padding:".28rem .75rem",border:`1px solid ${s.border}`,color:s.color,background:s.bg}}>{children}</span>;};

const Btn=({v="primary",sz="md",full,onClick,children,style={}})=>{const[h,setH]=useState(false);const sz2={sm:{padding:".5rem 1.1rem",fontSize:".5rem"},md:{padding:".8rem 1.8rem",fontSize:".54rem"},lg:{padding:"1rem 2.5rem",fontSize:".56rem"}};const vs={primary:{bg:T.brown,color:T.cream,border:T.brown},outline:{bg:"transparent",color:T.brown,border:T.brown},gold:{bg:T.gold,color:T.ivory,border:T.gold},ghost:{bg:"transparent",color:T.brown3,border:"transparent"}};const vt=vs[v]||vs.primary;const hv=h?(v==="primary"?{background:T.brown2}:v==="outline"?{background:T.brown,color:T.cream}:{}):{};return <button onClick={onClick} onMouseEnter={()=>setH(true)} onMouseLeave={()=>setH(false)} style={{display:"inline-flex",alignItems:"center",justifyContent:"center",gap:".5rem",fontFamily:"'Montserrat',sans-serif",fontWeight:500,letterSpacing:".18em",textTransform:"uppercase",background:vt.bg,color:vt.color,border:`1px solid ${vt.border}`,cursor:"pointer",transition:"all .3s",borderRadius:0,whiteSpace:"nowrap",...(sz2[sz]||sz2.md),...(full?{width:"100%"}:{}),...hv,...style}}>{children}</button>;};

const Card=({title,actions,children,style={}})=>(<div style={{background:T.ivory,marginBottom:"1rem",...style}}>{title&&<div style={{padding:"1rem 1.5rem",display:"flex",justifyContent:"space-between",alignItems:"center",borderBottom:`1px solid ${T.lineL}`,flexWrap:"wrap",gap:".5rem"}}><span style={{fontSize:".56rem",letterSpacing:".2em",textTransform:"uppercase",color:T.brown,fontWeight:500}}>{title}</span>{actions&&<div style={{display:"flex",gap:".5rem",flexWrap:"wrap"}}>{actions}</div>}</div>}{children}</div>);

const KPI=({label,value,sub,subColor,icon:Icon})=>(<div style={{background:T.ivory,padding:"1.4rem 1.5rem"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:".6rem"}}><div style={{fontSize:".46rem",letterSpacing:".2em",textTransform:"uppercase",color:T.brown3,fontWeight:500}}>{label}</div>{Icon&&<span style={{color:T.gold}}><Icon/></span>}</div><div style={{fontFamily:"'Cormorant Garamond',serif",fontSize:"1.9rem",fontWeight:400,lineHeight:1,color:T.brown,marginBottom:".3rem"}}>{value}</div>{sub&&<div style={{fontSize:".54rem",color:subColor||T.brown3}}>{sub}</div>}</div>);

const Alert=({type="gold",icon,children})=>{const colors={gold:{bg:T.goldL,border:"rgba(138,106,56,.25)",color:T.gold},red:{bg:T.redL,border:"rgba(139,58,58,.25)",color:T.red},green:{bg:T.greenL,border:"rgba(74,122,66,.25)",color:T.green},blue:{bg:T.blueL,border:"rgba(58,90,139,.25)",color:T.blue}};const c=colors[type]||colors.gold;const Icon=icon;return <div style={{background:c.bg,border:`1px solid ${c.border}`,padding:".9rem 1.2rem",marginBottom:".8rem",display:"flex",alignItems:"flex-start",gap:".75rem"}}>{Icon&&<span style={{color:c.color,flexShrink:0,marginTop:1}}><Icon/></span>}<div style={{fontSize:".6rem",lineHeight:1.85,color:T.brown2}}>{children}</div></div>;};

const Divider=()=>(<div style={{display:"flex",alignItems:"center",gap:"1.5rem",margin:"1.5rem 0"}}><div style={{flex:1,height:"0.5px",background:T.line}}/><span style={{fontFamily:"'Cormorant Garamond',serif",fontSize:".9rem",color:T.gold}}>✦</span><div style={{flex:1,height:"0.5px",background:T.line}}/></div>);

const Logo=()=>(<div><div style={{fontFamily:"'Cormorant Garamond',serif",fontSize:"1rem",letterSpacing:".2em",color:T.brown,whiteSpace:"nowrap",fontWeight:400}}>K PROPERTIES</div><div style={{display:"flex",alignItems:"center",gap:".5rem",marginTop:".25rem"}}><div style={{flex:1,height:"0.5px",background:T.gold}}/><div style={{fontSize:".3rem",letterSpacing:".3em",textTransform:"uppercase",color:T.gold,whiteSpace:"nowrap"}}>AFRIGROUPE · ABIDJAN</div><div style={{flex:1,height:"0.5px",background:T.gold}}/></div></div>);

const BarChart=()=>(<div style={{display:"flex",alignItems:"flex-end",gap:4,height:120}}>{["J","F","M","A","M","J","J","A","S","O","N","D"].map((l,i)=>(<div key={l} style={{display:"flex",flexDirection:"column",alignItems:"center",gap:3,flex:1}}><div style={{width:"100%",height:`${[25,40,35,55,50,65,75,60,70,80,85,68][i]}%`,background:`linear-gradient(to top,${T.gold},${T.goldL})`,borderTop:`1px solid ${T.gold}`}}/><div style={{fontSize:".4rem",color:T.brown3}}>{l}</div></div>))}</div>);

const TL=({items})=>(<div style={{padding:"1.2rem 1.5rem"}}>{items.map(([st,t,s,d],i)=>(<div key={i} style={{display:"flex",gap:"1rem",padding:".7rem 0",position:"relative"}}>{i<items.length-1&&<div style={{position:"absolute",left:9,top:22,width:1,height:"100%",background:T.lineL}}/>}<div style={{width:20,height:20,border:`1px solid ${st==="done"?T.gold:st==="active"?T.gold:T.line}`,background:st==="done"?T.gold:st==="active"?T.goldL:"transparent",display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0,marginTop:2,color:st==="done"?T.ivory:T.gold}}>{st==="done"&&<I.Check/>}{st==="active"&&<span style={{fontSize:".5rem",fontWeight:600}}>→</span>}</div><div style={{flex:1}}><div style={{fontSize:".62rem",fontWeight:500,color:st==="active"?T.gold:st==="pending"?T.brown3:T.brown,marginBottom:".2rem"}}>{t}</div><div style={{fontSize:".55rem",color:T.brown3}}>{s}</div></div><div style={{fontSize:".5rem",color:T.brown3,whiteSpace:"nowrap",flexShrink:0}}>{d}</div></div>))}</div>);

// ── LANDING ───────────────────────────────────────────────
function Landing({goto}){
  const w=useW(),isMobile=w<768;
  const PROJECTS=[["Résidentiel Premium · En cours","Résidence Cocody Heights","Cocody, Abidjan"],["Bureaux · Disponible","K Tower — Le Plateau","Le Plateau, Abidjan"],["Villas · Pré-vente","Jardins de Bingerville","Bingerville, Abidjan"],["Mixte · Lancement","Marcory Premium Center","Marcory, Abidjan"],["Résidentiel · Pipeline","Riviera Palms Estate","Riviera, Abidjan"]];
  return(<div style={{background:T.cream}}>
    <nav style={{position:"fixed",top:0,left:0,right:0,zIndex:200,background:`rgba(232,224,208,.96)`,backdropFilter:"blur(20px)",borderBottom:`1px solid ${T.lineL}`,padding:isMobile?"1.1rem 1.5rem":"1.3rem 4rem",display:"flex",justifyContent:"space-between",alignItems:"center"}}>
      <Logo/>
      <div style={{display:"flex",gap:".6rem"}}><Btn v="outline" sz="sm" onClick={()=>goto("auth")}>Connexion</Btn><Btn sz="sm" onClick={()=>goto("auth")}>Accès Privé</Btn></div>
    </nav>
    {/* HERO */}
    <div style={{minHeight:"100vh",display:"flex",alignItems:"center",padding:isMobile?"7rem 1.5rem 5rem":"0 4rem",position:"relative",overflow:"hidden",background:T.ivory}}>
      {!isMobile&&<div style={{position:"absolute",right:"-5%",top:"50%",transform:"translateY(-50%)",fontFamily:"'Cormorant Garamond',serif",fontSize:"38vw",fontWeight:200,color:"transparent",WebkitTextStroke:`1px rgba(26,14,8,.04)`,lineHeight:1,pointerEvents:"none",userSelect:"none"}}>K</div>}
      <div style={{position:"relative",zIndex:2,maxWidth:600,animation:"fadeUp 1s ease .1s both"}}>
        <div style={{fontSize:".48rem",letterSpacing:".4em",textTransform:"uppercase",color:T.gold,marginBottom:"1.2rem",display:"flex",alignItems:"center",gap:"1rem"}}><span style={{width:22,height:"0.5px",background:T.gold,display:"inline-block"}}/>Abidjan · Côte d'Ivoire · AFRIGROUPE</div>
        <h1 style={{fontFamily:"'Cormorant Garamond',serif",fontSize:isMobile?"clamp(3rem,14vw,4.5rem)":"clamp(3.5rem,7vw,5.5rem)",fontWeight:300,lineHeight:1,color:T.brown,marginBottom:".8rem"}}>Built for<br/>the Few.</h1>
        <p style={{fontFamily:"'Cormorant Garamond',serif",fontSize:isMobile?"1.1rem":"1.5rem",fontWeight:300,fontStyle:"italic",color:T.brown2,marginBottom:"2rem",lineHeight:1.4}}>Own the exception. Where prestige meets purpose.</p>
        <div style={{width:40,height:"0.5px",background:T.gold,marginBottom:"2rem"}}/>
        <p style={{fontSize:".68rem",lineHeight:2.2,color:T.brown2,maxWidth:420,marginBottom:"3rem"}}>We are not a real estate agency, we are a premium experience. We don't sell properties, we build relationships.</p>
        <div style={{display:"flex",flexDirection:isMobile?"column":"row",gap:".8rem"}}>
          <Btn sz="lg" onClick={()=>goto("kyc")} style={isMobile?{width:"100%"}:{}}>Soumettre ma candidature</Btn>
          <Btn v="outline" sz="lg" style={isMobile?{width:"100%"}:{}}>Découvrir les projets</Btn>
        </div>
      </div>
    </div>
    {/* QUOTE */}
    <div style={{background:T.brown,padding:isMobile?"3.5rem 1.5rem":"4rem",textAlign:"center"}}>
      <div style={{maxWidth:560,margin:"0 auto"}}>
        <div style={{fontFamily:"'Cormorant Garamond',serif",fontSize:isMobile?"1.5rem":"2rem",fontWeight:300,fontStyle:"italic",color:T.cream,lineHeight:1.5,marginBottom:"1.5rem"}}>"Là où d'autres proposent des biens,<br/>nous bâtissons des relations."</div>
        <div style={{display:"flex",alignItems:"center",gap:"1.5rem"}}><div style={{flex:1,height:"0.5px",background:"rgba(245,240,232,.2)"}}/><span style={{fontSize:".46rem",letterSpacing:".38em",textTransform:"uppercase",color:T.beige}}>K PROPERTIES · AFRIGROUPE</span><div style={{flex:1,height:"0.5px",background:"rgba(245,240,232,.2)"}}/></div>
      </div>
    </div>
    {/* PROJECTS */}
    <div style={{background:T.cream2,padding:isMobile?"4rem 1.5rem":"7rem 4rem"}}>
      <div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-end",marginBottom:"3rem",flexWrap:"wrap",gap:"1rem"}}>
        <div><div style={{fontSize:".48rem",letterSpacing:".4em",textTransform:"uppercase",color:T.gold,marginBottom:"1.2rem",display:"flex",alignItems:"center",gap:"1rem"}}><span style={{width:22,height:"0.5px",background:T.gold,display:"inline-block"}}/>Portfolio</div><h2 style={{fontFamily:"'Cormorant Garamond',serif",fontSize:"clamp(2rem,5vw,3.2rem)",fontWeight:300,color:T.brown}}>Projets d'exception</h2></div>
        <Btn v="outline" sz="sm" onClick={()=>goto("auth")}>Accès membres →</Btn>
      </div>
      <div style={{display:"flex",flexDirection:"column",gap:2}}>
        {PROJECTS.map(([tag,name,loc],i)=>(<div key={name} onClick={()=>goto("auth")} style={{position:"relative",overflow:"hidden",cursor:"pointer",background:`linear-gradient(${i%2===0?"150deg":"135deg"},${T.brown},${T.brown2})`,height:isMobile?190:i===0?280:200}}><div style={{position:"absolute",inset:0,background:"linear-gradient(to top,rgba(26,14,8,.92) 0%,rgba(26,14,8,.2) 55%,transparent 100%)",padding:"1.5rem",display:"flex",flexDirection:"column",justifyContent:"flex-end"}}><div style={{fontSize:".44rem",letterSpacing:".25em",textTransform:"uppercase",color:T.beige,marginBottom:".5rem",display:"flex",alignItems:"center",gap:".6rem"}}><span style={{width:14,height:"0.5px",background:T.beige,display:"inline-block"}}/>{tag}</div><div style={{fontFamily:"'Cormorant Garamond',serif",fontSize:i===0&&!isMobile?"1.6rem":"1.2rem",fontWeight:400,color:T.cream,marginBottom:".3rem"}}>{name}</div><div style={{fontSize:".54rem",color:"rgba(245,240,232,.5)"}}>{loc}</div><div style={{fontSize:".5rem",color:T.beige,marginTop:".6rem"}}>Prix & plans sur dossier →</div></div></div>))}
      </div>
      <div style={{textAlign:"center",marginTop:"3rem"}}><p style={{fontSize:".58rem",color:T.brown3,marginBottom:"1.5rem"}}>Prix, plans et brochures réservés aux membres vérifiés · KYC 200M FCFA minimum</p><Btn v="outline" onClick={()=>goto("auth")}>Soumettre ma candidature</Btn></div>
    </div>
    {/* PORTALS */}
    <div style={{background:T.ivory,padding:isMobile?"4rem 1.5rem":"7rem 4rem"}}>
      <div style={{fontSize:".48rem",letterSpacing:".4em",textTransform:"uppercase",color:T.gold,marginBottom:"1.2rem",display:"flex",alignItems:"center",gap:"1rem"}}><span style={{width:22,height:"0.5px",background:T.gold,display:"inline-block"}}/>Portails d'accès</div>
      <h2 style={{fontFamily:"'Cormorant Garamond',serif",fontSize:"clamp(2rem,5vw,3.2rem)",fontWeight:300,color:T.brown,marginBottom:"3.5rem"}}>Two portals.<br/>One standard.</h2>
      <div style={{display:"grid",gridTemplateColumns:isMobile?"1fr":"1fr 1fr",gap:isMobile?"1rem":"2px"}}>
        {[[I.Person,"Acquéreurs","Pour les particuliers et investisseurs souhaitant acquérir des biens d'exception. Accès après vérification KYC complète.",["Portfolio projets","Suivi dossier temps réel","Tableau de bord financier","Documents sécurisés","Messagerie conseiller","Calendrier RDV"],"Candidater","outline",false],[I.Handshake,"Partenaires","Accès exclusif sur invitation, réservé aux professionnels qualifiés souhaitant accompagner leurs clients.",["Accès sur invitation","Espace dédié & outils","Accompagnement sur mesure","Catalogue projets","Support 6j/7","Conditions préférentielles"],"Demander un accès","gold",true]].map(([Icon,title,desc,features,cta,v,dark],i)=>(<div key={title} onClick={()=>goto("auth")} style={{background:dark?T.brown:T.cream2,padding:isMobile?"2rem 1.5rem":"3.5rem",cursor:"pointer",position:"relative",overflow:"hidden"}}><div style={{position:"absolute",top:0,right:0,width:60,height:60,borderLeft:`1px solid ${dark?"rgba(245,240,232,.08)":T.line}`,borderBottom:`1px solid ${dark?"rgba(245,240,232,.08)":T.line}`}}/><div style={{width:46,height:46,border:`1px solid ${dark?"rgba(245,240,232,.15)":T.line}`,display:"flex",alignItems:"center",justifyContent:"center",marginBottom:"2rem",color:dark?T.beige:T.gold}}><Icon/></div><h3 style={{fontFamily:"'Cormorant Garamond',serif",fontSize:"1.6rem",fontWeight:400,marginBottom:"1rem",color:dark?T.cream:T.brown}}>{title}</h3><p style={{fontSize:".63rem",lineHeight:2,color:dark?"rgba(245,240,232,.5)":T.brown2,marginBottom:"2rem"}}>{desc}</p><Divider/><ul style={{listStyle:"none",marginBottom:"2.5rem"}}>{features.map(f=>(<li key={f} style={{fontSize:".58rem",color:dark?"rgba(245,240,232,.55)":T.brown2,padding:".6rem 0",borderBottom:`1px solid ${dark?"rgba(245,240,232,.06)":T.lineL}`,display:"flex",alignItems:"center",gap:".7rem"}}><I.Check/>{f}</li>))}</ul><Btn v={v} full>{cta}</Btn></div>))}
      </div>
    </div>
    {/* FOOTER */}
    <div style={{background:T.brown,padding:"3rem 1.5rem"}}><Logo/><div style={{height:"0.5px",background:"rgba(245,240,232,.12)",margin:"1.5rem 0"}}/><div style={{display:"flex",flexDirection:isMobile?"column":"row",justifyContent:"space-between",gap:".5rem"}}><div style={{fontSize:".48rem",color:"rgba(245,240,232,.3)"}}>© 2024 K Properties · AFRIGROUPE · Abidjan</div><div style={{fontSize:".48rem",color:"rgba(245,240,232,.3)"}}>contact@kproperties.ci</div></div></div>
  </div>);
}

// ── AUTH ──────────────────────────────────────────────────
function Auth({goto,loginAs}){
  const[tab,setTab]=useState("login");
  const w=useW(),isMobile=w<768;
  return(<div style={{minHeight:"100vh",background:T.cream}}>
    <div style={{padding:"1.5rem 2rem",borderBottom:`1px solid ${T.lineL}`,display:"flex",justifyContent:"space-between",alignItems:"center",background:T.ivory}}><Logo/><span onClick={()=>goto("landing")} style={{fontSize:".5rem",letterSpacing:".15em",color:T.brown2,cursor:"pointer"}}>← Retour</span></div>
    <div style={{maxWidth:420,margin:"0 auto",padding:isMobile?"2.5rem 1.5rem":"4rem 2rem"}}>
      <div style={{textAlign:"center",marginBottom:"3rem"}}><h2 style={{fontFamily:"'Cormorant Garamond',serif",fontSize:"2.5rem",fontWeight:300,color:T.brown,marginBottom:".8rem",lineHeight:1.1}}>Accès<br/><em style={{fontStyle:"italic",color:T.brown3}}>exclusif</em></h2><p style={{fontSize:".6rem",color:T.brown3,lineHeight:1.9}}>Plateforme réservée aux membres vérifiés.<br/>KYC 5 étapes · 200M FCFA minimum.</p></div>
      <div style={{display:"flex",borderBottom:`1px solid ${T.line}`,marginBottom:"2.5rem"}}>{[["login","Connexion"],["register","Inscription"]].map(([t,l])=>(<div key={t} onClick={()=>setTab(t)} style={{flex:1,textAlign:"center",fontSize:".52rem",letterSpacing:".18em",textTransform:"uppercase",padding:".8rem",cursor:"pointer",color:tab===t?T.brown:T.brown3,borderBottom:tab===t?`1px solid ${T.brown}`:"1px solid transparent",marginBottom:"-1px"}}>{l}</div>))}</div>
      {tab==="login"?(<div>
        <div style={{marginBottom:"1.8rem"}}><label>Email</label><input type="email" placeholder="votre@email.com"/></div>
        <div style={{marginBottom:"1.8rem"}}><label>Mot de passe</label><input type="password" placeholder="••••••••"/></div>
        <Btn full onClick={()=>loginAs("client")} style={{marginBottom:"2rem"}}>Se connecter</Btn>
        <Divider/><p style={{fontSize:".5rem",color:T.brown3,textAlign:"center",marginBottom:"1.2rem"}}>Accès démonstration</p>
        <div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:".6rem"}}>
          <Btn v="outline" sz="sm" onClick={()=>loginAs("client")}>Client</Btn>
          <Btn v="outline" sz="sm" onClick={()=>loginAs("partner")}>Partenaire</Btn>
          <Btn v="outline" sz="sm" onClick={()=>loginAs("admin")}>Admin</Btn>
        </div>
      </div>):(<div>
        <div style={{marginBottom:"1.5rem"}}><label>Type de compte</label><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:".8rem",marginTop:".5rem"}}>{[[I.Person,"Acquéreur"],[I.Handshake,"Partenaire"]].map(([Icon,lb])=>(<div key={lb} style={{border:`1px solid ${T.lineL}`,padding:"1rem",cursor:"pointer",textAlign:"center"}}><div style={{display:"flex",justifyContent:"center",marginBottom:".4rem",color:T.gold}}><Icon/></div><div style={{fontSize:".5rem",color:T.brown3}}>{lb}</div></div>))}</div></div>
        <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"1rem",marginBottom:"1.5rem"}}><div><label>Prénom</label><input placeholder="Jean"/></div><div><label>Nom</label><input placeholder="Kouassi"/></div></div>
        <div style={{marginBottom:"1.5rem"}}><label>Email</label><input type="email" placeholder="j.kouassi@email.com"/></div>
        <div style={{marginBottom:"2rem"}}><label>Téléphone</label><input placeholder="+225 07 00 00 00 00"/></div>
        <Btn full onClick={()=>goto("kyc")}>Soumettre ma candidature →</Btn>
      </div>)}
    </div>
  </div>);
}

// ── KYC ───────────────────────────────────────────────────
function KYC({goto,loginAs}){
  const[step,setStep]=useState(1);
  const[done,setDone]=useState(false);
  const w=useW(),isMobile=w<768;
  const steps=["Identité","Profil","Fonds","Documents","Signature"];
  const FG=({label,children})=><div style={{marginBottom:"1.5rem"}}><label>{label}</label>{children}</div>;
  const Sel=({opts})=><select style={{borderBottom:`1px solid ${T.brown}`}}><option>Sélectionner</option>{opts.map(o=><option key={o}>{o}</option>)}</select>;
  const Up=({label,desc})=><FG label={label}><div style={{border:`1px solid ${T.line}`,padding:"2rem",textAlign:"center",cursor:"pointer"}}><I.Download/><div style={{fontSize:".58rem",color:T.brown2,marginTop:".5rem"}}>Glissez ou <span style={{color:T.gold}}>parcourez</span></div>{desc&&<div style={{fontSize:".52rem",color:T.brown3,marginTop:".3rem"}}>{desc}</div>}</div></FG>;
  const views={
    1:<div><Alert icon={I.Shield} type="blue">Ces informations garantissent la sécurité de tous les membres. Chiffrées AES-256.</Alert><div style={{display:"grid",gridTemplateColumns:isMobile?"1fr":"1fr 1fr",gap:"1.5rem",marginBottom:"1.5rem"}}><FG label="Prénom *"><input placeholder="Jean"/></FG><FG label="Nom *"><input placeholder="Kouassi"/></FG></div><FG label="Nationalité *"><Sel opts={["Ivoirienne","Française","Sénégalaise","Ghanéenne","Autre"]}/></FG><FG label="Pays de résidence *"><Sel opts={["Côte d'Ivoire","France","Sénégal","Ghana","Maroc","Autre"]}/></FG><FG label="Adresse complète *"><input placeholder="Cocody, Abidjan, Côte d'Ivoire"/></FG><div style={{display:"grid",gridTemplateColumns:isMobile?"1fr":"1fr 1fr",gap:"1.5rem",marginBottom:"1.5rem"}}><FG label="Téléphone *"><input placeholder="+225 07 00 00 00 00"/></FG><FG label="Email *"><input type="email" placeholder="j.kouassi@email.com"/></FG></div><FG label="Profession *"><Sel opts={["Chef d'entreprise","Directeur Général","Investisseur","Médecin","Autre"]}/></FG></div>,
    2:<div><Alert icon={I.Chart} type="gold">Seuil minimum : <strong>200M FCFA</strong>. Ces informations valident l'adéquation avec nos projets.</Alert><FG label="Revenus annuels nets *"><Sel opts={["60M–150M FCFA","150M–300M FCFA","300M–600M FCFA","+ 600M FCFA"]}/></FG><FG label="Patrimoine global estimé *"><Sel opts={["200M–500M FCFA","500M–1Md FCFA","1Md–3Md FCFA","+ 3Md FCFA"]}/></FG><FG label="Capacité d'investissement *"><Sel opts={["200M–400M FCFA","400M–800M FCFA","800M–1.5Md FCFA","+ 1.5Md FCFA"]}/></FG><FG label="Objectif d'acquisition *"><Sel opts={["Résidence principale","Investissement locatif","Diversification patrimoniale","Résidence secondaire"]}/></FG><FG label="Horizon de placement *"><Sel opts={["Court terme (- 2 ans)","Moyen terme (2-7 ans)","Long terme (7 ans +)"]}/></FG></div>,
    3:<div><Alert icon={I.Warning} type="red">K Properties est soumis aux réglementations AML/KYC. Toute fausse déclaration entraîne un rejet immédiat.</Alert><FG label="Source principale des fonds *"><Sel opts={["Revenus salariés","Bénéfices d'entreprise","Cession d'actifs","Héritage","Revenus locatifs","Épargne"]}/></FG><FG label="Banque principale *"><input placeholder="Nom de votre banque"/></FG><FG label="Pays de la banque *"><Sel opts={["Côte d'Ivoire","France","Sénégal","Ghana","Maroc","Suisse","Luxembourg","Autre"]}/></FG><FG label="Êtes-vous une Personne Politiquement Exposée (PPE) ? *"><Sel opts={["Non","Oui — Fonction actuelle","Oui — Fonction passée","Famille d'une PPE"]}/></FG></div>,
    4:<div><Alert icon={I.Lock} type="blue">Tous vos fichiers sont chiffrés AES-256. Seule l'équipe de conformité K Properties y a accès.</Alert><Up label="Pièce d'identité (Passeport ou CNI recto-verso) *" desc="PDF, JPG, PNG · Max 10 Mo"/><Up label="Justificatif de domicile (- 3 mois) *" desc="Facture eau, électricité ou relevé bancaire"/><Up label="3 derniers relevés bancaires *" desc="Banque principale · PDF officiel"/><Up label="Justificatif de revenus *" desc="Bulletins de salaire ou bilan comptable certifié"/></div>,
    5:<div><Alert icon={I.Check} type="green">En soumettant, vous acceptez que K Properties procède aux vérifications. Délai : <strong>5 jours ouvrables</strong>.</Alert><Up label="NDA signé *" desc="Téléchargez, signez et renvoyez le NDA K Properties"/>{["Je certifie l'exactitude de toutes les informations fournies.","J'accepte la politique de confidentialité.","J'accepte les conditions générales d'utilisation."].map(t=>(<label key={t} style={{display:"flex",alignItems:"flex-start",gap:"1rem",cursor:"pointer",marginBottom:"1.2rem"}}><input type="checkbox" style={{width:16,height:16,flexShrink:0,marginTop:2,accentColor:T.brown}}/><span style={{fontSize:".58rem",lineHeight:1.9,color:T.brown2}}>{t}</span></label>))}<FG label="Signature électronique — Nom complet *"><input placeholder="Jean Kouassi"/></FG></div>
  };
  if(done) return(<div style={{display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",minHeight:"100vh",textAlign:"center",padding:"3rem 1.5rem",background:T.ivory}}><div style={{color:T.gold,marginBottom:"1.5rem"}}><I.Check/></div><h2 style={{fontFamily:"'Cormorant Garamond',serif",fontSize:"2rem",fontWeight:300,color:T.brown,marginBottom:"1.5rem"}}>Dossier soumis</h2><p style={{fontSize:".66rem",color:T.brown2,lineHeight:2,maxWidth:380,marginBottom:"2.5rem"}}>Notre équipe vous contactera dans les <strong>5 jours ouvrables</strong>.</p><div style={{background:T.cream2,border:`1px solid ${T.line}`,padding:"1.8rem 2.5rem",marginBottom:"2.5rem"}}><div style={{fontSize:".48rem",letterSpacing:".2em",textTransform:"uppercase",color:T.gold,marginBottom:".6rem"}}>Référence dossier</div><div style={{fontFamily:"'Cormorant Garamond',serif",fontSize:"1.5rem",color:T.brown}}>KP-2024-0847</div></div><Btn sz="lg" onClick={()=>loginAs("client")} style={{width:"100%",maxWidth:300}}>Accéder à mon espace →</Btn></div>);
  return(<div style={{background:T.cream}}>
    <div style={{background:T.ivory,padding:"1.2rem 1.5rem",borderBottom:`1px solid ${T.lineL}`,position:"sticky",top:0,zIndex:100}}>
      <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:".8rem"}}><div style={{fontFamily:"'Cormorant Garamond',serif",fontSize:".95rem",color:T.brown}}>KYC — Étape {step}/5</div><Btn v="ghost" sz="sm" onClick={()=>goto("landing")}>Quitter</Btn></div>
      <div style={{height:1,background:T.line}}><div style={{height:"100%",width:`${(step/5)*100}%`,background:T.gold,transition:"width .4s ease"}}/></div>
      <div style={{display:"flex",justifyContent:"space-between",marginTop:".5rem"}}>{steps.map((s,i)=><div key={s} style={{fontSize:".42rem",textTransform:"uppercase",color:i+1<=step?T.gold:T.brown3}}>{s}</div>)}</div>
    </div>
    <div style={{maxWidth:580,margin:"0 auto",padding:"3rem 1.5rem 6rem"}}>
      <h2 style={{fontFamily:"'Cormorant Garamond',serif",fontSize:"1.9rem",fontWeight:300,color:T.brown,marginBottom:".5rem"}}>{["Identité & Coordonnées","Profil Investisseur","Origine des Fonds","Documents Justificatifs","Signature & Engagement"][step-1]}</h2>
      <div style={{width:30,height:"0.5px",background:T.gold,marginBottom:"2.5rem"}}/>
      {views[step]}
      <div style={{display:"flex",gap:".8rem",marginTop:"2rem"}}>
        {step>1&&<Btn v="outline" onClick={()=>setStep(s=>s-1)}>← Retour</Btn>}
        {step<5?<Btn onClick={()=>setStep(s=>s+1)} style={step===1?{width:"100%"}:{flex:1}}>Continuer →</Btn>:<Btn onClick={()=>setDone(true)} style={{flex:1}}>Soumettre mon dossier →</Btn>}
      </div>
      {step<5&&<div style={{textAlign:"center",marginTop:"1.5rem"}}><span onClick={()=>goto("landing")} style={{fontSize:".54rem",color:T.gold,cursor:"pointer",textDecoration:"underline"}}>Prendre un rendez-vous avec un conseiller →</span></div>}
    </div>
  </div>);
}

// ── DASHBOARD ─────────────────────────────────────────────
const NAVS={
  client:[{s:"Mon Acquisition"},{id:"overview",ic:I.Home,lb:"Vue globale"},{id:"dossier",ic:I.Doc,lb:"Mon dossier"},{id:"financier",ic:I.Money,lb:"Tableau financier",b:1},{id:"chantier",ic:I.Building,lb:"Suivi chantier"},{s:"Projets"},{id:"projets",ic:I.Map,lb:"Bibliothèque projets"},{id:"simulateur",ic:I.Chart,lb:"Simulateur financier"},{s:"Communication"},{id:"messagerie",ic:I.Message,lb:"Messagerie",b:3},{id:"rdv",ic:I.Calendar,lb:"Rendez-vous"},{s:"Documents"},{id:"documents",ic:I.Doc,lb:"Mes documents"},{id:"kyc",ic:I.Shield,lb:"Mon profil & KYC"},{s:"Avantages"},{id:"parrainage",ic:I.Handshake,lb:"Parrainage"},{s:"Support"},{id:"notifications",ic:I.Bell,lb:"Notifications",b:3},{id:"settings",ic:I.Gear,lb:"Paramètres"}],
  partner:[{s:"Principal"},{id:"overview",ic:I.Home,lb:"Vue globale"},{id:"crm",ic:I.Users,lb:"CRM Clients"},{id:"commissions",ic:I.Money,lb:"Commissions"},{s:"Projets"},{id:"catalogue",ic:I.Building,lb:"Catalogue projets"},{id:"outils",ic:I.Book,lb:"Outils commercialisation"},{s:"Performance"},{id:"stats",ic:I.Chart,lb:"Mes statistiques"},{id:"vip",ic:I.Star,lb:"Statut VIP"},{s:"Formation"},{id:"formation",ic:I.Academic,lb:"Formation & Certification"},{s:"Communication"},{id:"messagerie",ic:I.Message,lb:"Messagerie",b:2},{id:"agenda",ic:I.Calendar,lb:"Agenda & RDV"},{s:"Mon Compte"},{id:"profil",ic:I.Person,lb:"Profil & Accréditations"},{id:"settings",ic:I.Gear,lb:"Paramètres"}],
  admin:[{s:"Administration"},{id:"overview",ic:I.Home,lb:"Vue globale"},{id:"alertes",ic:I.Warning,lb:"Alertes urgentes",b:7},{id:"kyc",ic:I.Shield,lb:"Validation KYC",b:12},{s:"Membres"},{id:"membres",ic:I.Users,lb:"Gestion membres"},{id:"leads",ic:I.Inbox,lb:"Leads entrants",b:8},{s:"Projets & Finance"},{id:"projets",ic:I.Building,lb:"Gestion projets"},{id:"finance",ic:I.Chart,lb:"Reporting financier"},{id:"commissions",ic:I.Money,lb:"Commissions"},{s:"Commercial"},{id:"crm",ic:I.Trend,lb:"CRM Pipeline"},{s:"Communication"},{id:"messagerie",ic:I.Message,lb:"Messagerie",b:5},{id:"agenda",ic:I.Calendar,lb:"Agenda & RDV"},{s:"Partenaires"},{id:"partenaires",ic:I.Handshake,lb:"Gestion partenaires"},{s:"Outils"},{id:"exports",ic:I.Download,lb:"Exports & Rapports"},{id:"settings",ic:I.Gear,lb:"Paramètres"}],
};
const INFO={client:{ini:"JK",name:"Jean Kouassi",role:"Acquéreur Vérifié",label:"Espace Client"},partner:{ini:"CA",name:"Me Camille Adou",role:"Partenaire Gold ✦",label:"Espace Partenaire"},admin:{ini:"KP",name:"Admin K Properties",role:"Super Admin",label:"Back-Office Admin"}};

function DView({role,view,setView}){
  const w=useW(),isMobile=w<768;
  const Ks=({items,cols=4})=>(<div style={{display:"grid",gridTemplateColumns:isMobile?"1fr 1fr":`repeat(${cols},1fr)`,gap:1,marginBottom:"1rem"}}>{items.map(([l,v,s,sc,Ic])=><KPI key={l} label={l} value={v} sub={s} subColor={sc==="up"?T.green:sc==="warn"?T.gold:sc==="red"?T.red:undefined} icon={Ic}/>)}</div>);

  // CLIENT
  if(role==="client"){
    if(view==="overview") return <div>
      <Alert icon={I.Warning} type="gold"><strong>Action requise :</strong> Contrat Cocody Heights prêt à signer. Délai : 72h. <Btn sz="sm" style={{marginLeft:"1rem"}} onClick={()=>setView("documents")}>Voir →</Btn></Alert>
      <Ks items={[["KYC","Vérifié ✓","08 Nov 2024","up",I.Shield],["Dossiers actifs","2","En cours","",I.Doc],["Montant engagé","205M","FCFA","",I.Money],["Messages","3","Non lus","warn",I.Message]]}/>
      <div style={{display:"grid",gridTemplateColumns:isMobile?"1fr":"2fr 1fr",gap:1,marginBottom:"1rem"}}>
        <Card title="Mes acquisitions" actions={<Btn v="ghost" sz="sm" onClick={()=>setView("dossier")}>Voir →</Btn>}>
          <div style={{padding:"1.2rem 1.5rem"}}>
            {[["Résidence Cocody Heights","Cocody · 85M FCFA","Signature notariale","gold"],["K Tower — Le Plateau","Plateau · 120M FCFA","Négociation","beige"]].map(([n,s,st,c])=>(<div key={n} style={{padding:"1rem 0",borderBottom:`1px solid ${T.lineL}`}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:".5rem"}}><div style={{fontFamily:"'Cormorant Garamond',serif",fontSize:".95rem",color:T.brown}}>{n}</div><Tag c={c}>{st}</Tag></div><div style={{fontSize:".54rem",color:T.brown3}}>{s}</div></div>))}
          </div>
        </Card>
        <Card title="Prochain versement">
          <div style={{padding:"1.5rem",textAlign:"center"}}>
            <div style={{fontFamily:"'Cormorant Garamond',serif",fontSize:"1.8rem",color:T.brown,marginBottom:".3rem"}}>17M FCFA</div>
            <div style={{fontSize:".56rem",color:T.gold,marginBottom:".8rem",fontWeight:500}}>20 Novembre 2024</div>
            <div style={{height:2,background:T.lineL,marginBottom:".5rem"}}><div style={{width:"30%",height:"100%",background:T.gold}}/></div>
            <div style={{display:"flex",justifyContent:"space-between",marginBottom:"1.2rem"}}><span style={{fontSize:".52rem",color:T.green}}>25.5M versés</span><span style={{fontSize:".52rem",color:T.brown3}}>59.5M restants</span></div>
            <Btn full sz="sm" onClick={()=>setView("financier")}>Voir l'échéancier</Btn>
          </div>
        </Card>
      </div>
      <Card title="Derniers messages" actions={<Btn v="ghost" sz="sm" onClick={()=>setView("messagerie")}>Tout voir →</Btn>}>
        {[["Conseiller K Properties","RDV 20 nov à 14h30 confirmé","2h",true],["Me Camille Adou","Documents bien reçus","Hier",false],["Support K Properties","Contrat prêt à signer","12 Nov",true]].map(([n,p,t,u])=>(<div key={n} onClick={()=>setView("messagerie")} style={{padding:".9rem 1.5rem",borderBottom:`1px solid ${T.lineL}`,borderLeft:u?`2px solid ${T.gold}`:"2px solid transparent",cursor:"pointer",display:"flex",justifyContent:"space-between",alignItems:"center",gap:"1rem"}}><div style={{flex:1,overflow:"hidden"}}><div style={{fontSize:".6rem",fontWeight:500,color:T.brown,marginBottom:".2rem"}}>{n}</div><div style={{fontSize:".55rem",color:T.brown3,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{p}</div></div><span style={{fontSize:".48rem",color:T.brown3,flexShrink:0}}>{t}</span></div>))}
      </Card>
    </div>;
    if(view==="dossier") return <div><Ks items={[["KYC","Vérifié ✓","","up",I.Shield],["Réf.","KP-0847","","",I.Key],["Validé","08 Nov","2024","",I.Calendar],["Conseiller","M. Koné","Disponible","up",I.Person]]} cols={4}/><Card title="Suivi — Résidence Cocody Heights" actions={<Tag c="gold">En cours</Tag>}><TL items={[["done","Dossier KYC validé","Vérification complétée","08 Nov"],["done","Présentation projet","Brochure & plans","10 Nov"],["done","Visite chantier","Avec le commercial","15 Nov"],["done","Offre acceptée","85 000 000 FCFA","12 Nov"],["active","Signature notariale","Me Camille Adou · 14h30","20 Nov"],["pending","Versement 2ème tranche","17M FCFA avant signature","20 Nov"],["pending","Remise des clés","Livraison T2 2026","T2 2026"]]}/></Card></div>;
    if(view==="financier") return <div><Ks items={[["Total","85M","FCFA","",I.Money],["Versé","25.5M","30% ✓","up",I.Check],["Restant","59.5M","FCFA","",I.Chart],["Prochain","17M","20 Nov","warn",I.Warning]]} cols={4}/><Alert icon={I.Warning} type="gold"><strong>Versement requis :</strong> 17 000 000 FCFA avant le 20 novembre pour confirmer la signature.</Alert><Card title="Échéancier — Cocody Heights"><table><thead><tr><th>#</th><th>Échéance</th><th>Montant</th><th>Statut</th></tr></thead><tbody>{[["1","08 Nov","25 500 000 FCFA","green","Payé ✓"],["2","20 Nov","17 000 000 FCFA","orange","À payer"],["3","20 Jan 2025","17 000 000 FCFA","silver","À venir"],["4","20 Avr","12 750 000 FCFA","silver","À venir"],["5","T2 2026","12 750 000 FCFA","silver","Livraison"]].map(([n,d,m,c,st])=>(<tr key={n}><td>{n}</td><td>{d}</td><td style={{fontWeight:500}}>{m}</td><td><Tag c={c}>{st}</Tag></td></tr>))}</tbody></table></Card></div>;
    if(view==="chantier") return <div><Ks items={[["Avancement","73%","Cocody Heights","up",I.Building],["MAJ","15 Nov","Photos ajoutées","",I.Camera],["Livraison","T2 2026","18 mois","",I.Calendar],["Statut","Dans les délais","","up",I.Check]]} cols={4}/><Card title="Résidence Cocody Heights — Avancement" actions={<Tag c="green">Dans les délais</Tag>}><div style={{padding:"1.5rem"}}><div style={{height:4,background:T.lineL,marginBottom:"1.2rem"}}><div style={{width:"73%",height:"100%",background:T.gold}}/></div><div style={{display:"grid",gridTemplateColumns:"repeat(5,1fr)",gap:".5rem",marginBottom:"1.5rem"}}>{[["Fondations","100%","green"],["Gros œuvre","85%","green"],["Second œuvre","45%","gold"],["Finitions","0%","silver"],["Réception","0%","silver"]].map(([ph,p,c])=>(<div key={ph} style={{textAlign:"center",background:T.cream2,padding:".8rem .5rem"}}><div style={{fontFamily:"'Cormorant Garamond',serif",fontSize:"1.2rem",color:c==="green"?T.green:c==="gold"?T.gold:T.brown3}}>{p}</div><div style={{fontSize:".48rem",color:T.brown3,marginTop:".2rem"}}>{ph}</div></div>))}</div><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:".5rem"}}>{[1,2,3,4,5,6].map(i=>(<div key={i} style={{paddingBottom:"65%",background:`linear-gradient(135deg,${T.brown},${T.brown2})`,position:"relative"}}><div style={{position:"absolute",inset:0,display:"flex",alignItems:"center",justifyContent:"center",color:"rgba(245,240,232,.2)"}}><I.Camera/></div></div>))}</div></div></Card></div>;
    if(view==="projets") return <div>{[["Résidence Cocody Heights","Résidentiel · 48 unités","85M–150M FCFA","En cours","green"],["K Tower — Le Plateau","Bureaux · 32 unités","120M–250M FCFA","Disponible","blue"],["Jardins de Bingerville","Villas · 40 unités","200M–400M FCFA","Pré-vente","gold"],["Marcory Premium Center","Mixte · 24 unités","Sur dossier","Lancement","orange"],["Riviera Palms Estate","Résidentiel · 30 unités","Sur dossier","Pipeline","silver"]].map(([n,m,p,st,c])=>(<div key={n} style={{background:T.ivory,padding:"1.5rem",marginBottom:1,display:"flex",justifyContent:"space-between",alignItems:"center",flexWrap:"wrap",gap:"1rem"}}><div><div style={{fontFamily:"'Cormorant Garamond',serif",fontSize:"1.05rem",color:T.brown,marginBottom:".3rem"}}>{n}</div><div style={{fontSize:".56rem",color:T.brown3,marginBottom:".3rem"}}>{m} · <span style={{color:T.gold,fontWeight:500}}>{p}</span></div><Tag c={c}>{st}</Tag></div><div style={{display:"flex",gap:".5rem"}}><Btn v="outline" sz="sm"><I.Download/> Brochure</Btn><Btn sz="sm"><I.Eye/> Détails</Btn></div></div>))}</div>;
    if(view==="simulateur") return <Card title="Simulateur de financement"><div style={{padding:"2rem 1.5rem"}}><div style={{display:"grid",gridTemplateColumns:isMobile?"1fr":"1fr 1fr",gap:"2rem"}}><div><div style={{marginBottom:"1.5rem"}}><label>Prix du bien (FCFA)</label><input defaultValue="85000000"/></div><div style={{marginBottom:"1.5rem"}}><label>Apport (%)</label><input defaultValue="30"/></div><div style={{marginBottom:"1.5rem"}}><label>Durée (années)</label><input defaultValue="15"/></div><div style={{marginBottom:"1.5rem"}}><label>Taux annuel (%)</label><input defaultValue="7.5"/></div><Btn full>Calculer</Btn></div><div style={{background:T.cream2,padding:"1.5rem"}}><div style={{fontFamily:"'Cormorant Garamond',serif",fontSize:"1.1rem",color:T.brown,marginBottom:"1.2rem",paddingBottom:".8rem",borderBottom:`1px solid ${T.lineL}`}}>Résultat</div>{[["Apport (30%)","25 500 000 FCFA"],["À financer","59 500 000 FCFA"],["Mensualité","546 000 FCFA/mois"],["Durée","15 ans"],["Coût total crédit","98 280 000 FCFA"]].map(([l,v])=>(<div key={l} style={{display:"flex",justifyContent:"space-between",padding:".6rem 0",borderBottom:`1px solid ${T.lineL}`}}><span style={{fontSize:".56rem",color:T.brown3}}>{l}</span><span style={{fontSize:".62rem",color:T.brown,fontWeight:500}}>{v}</span></div>))}</div></div></div></Card>;
    if(view==="messagerie") return <Card><div style={{display:"flex",flexDirection:isMobile?"column":"row",height:isMobile?"auto":480}}><div style={{width:isMobile?"100%":230,borderRight:isMobile?"none":`1px solid ${T.lineL}`,borderBottom:isMobile?`1px solid ${T.lineL}`:"none",overflowY:"auto"}}>{[["Conseiller K Properties","RDV 20 nov confirmé","14h32",true],["Me Camille Adou","Documents bien reçus","Hier",false],["Support K Properties","Contrat prêt à signer","12 Nov",true]].map(([n,p,t,u],i)=>(<div key={i} style={{padding:"1rem 1.2rem",borderBottom:`1px solid ${T.lineL}`,cursor:"pointer",background:i===0?T.goldL:"transparent",borderLeft:u?`2px solid ${T.gold}`:"2px solid transparent"}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:".2rem"}}><span style={{fontSize:".6rem",fontWeight:500,color:T.brown}}>{n}</span><span style={{fontSize:".48rem",color:T.brown3}}>{t}</span></div><div style={{fontSize:".55rem",color:T.brown3,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{p}</div></div>))}</div><div style={{flex:1,display:"flex",flexDirection:"column",minHeight:isMobile?320:0}}><div style={{padding:".9rem 1.5rem",borderBottom:`1px solid ${T.lineL}`}}><div style={{fontSize:".63rem",fontWeight:500,color:T.brown}}>Conseiller K Properties</div><div style={{fontSize:".52rem",color:T.brown3}}>En ligne</div></div><div style={{flex:1,padding:"1.2rem",overflowY:"auto",display:"flex",flexDirection:"column",gap:".8rem",background:T.ivory}}>{[["in","Bonjour M. Kouassi, votre dossier KYC a été validé."],["out","Merci. Quelles sont les prochaines étapes ?"],["in","Votre contrat est prêt. Signature le 20 novembre à 14h30."],["in","Votre 2ème versement de 17M est attendu avant cette date."]].map(([d,t],i)=>(<div key={i} style={{maxWidth:"78%",padding:".85rem 1rem",fontSize:".62rem",lineHeight:1.8,alignSelf:d==="out"?"flex-end":"flex-start",background:d==="in"?T.cream2:T.brown,color:d==="in"?T.brown:T.cream}}>{t}</div>))}</div><div style={{padding:".9rem 1.5rem",borderTop:`1px solid ${T.lineL}`,display:"flex",gap:".7rem",background:T.ivory}}><input placeholder="Écrire..." style={{flex:1}}/><Btn sz="sm">Envoyer</Btn></div></div></div></Card>;
    if(view==="rdv") return <div><Alert icon={I.Calendar} type="gold"><strong>Rappel :</strong> Signature notariale 20 novembre à 14h30 — Cabinet Adou, Le Plateau.</Alert><Card title="Mes rendez-vous" actions={<Btn sz="sm"><I.Plus/> RDV</Btn>}><TL items={[["done","Présentation portfolio","Conseiller K Properties","10 Nov"],["done","Visite chantier","Cocody Heights","15 Nov"],["active","Signature notariale","Me Camille Adou","20 Nov · 14h30"],["pending","Remise des clés","Livraison T2 2026","T2 2026"]]}/></Card></div>;
    if(view==="documents") return <div><Alert icon={I.Warning} type="gold"><strong>Action requise :</strong> Contrat de réservation prêt à signer. Délai : 72h.</Alert><Card title="Mes documents"><table><thead><tr><th>Document</th><th>Type</th><th>Date</th><th></th></tr></thead><tbody>{[["Contrat de réservation ✍","gold","Contrat","15 Nov"],["Plan unité A-304","beige","Plans","13 Nov"],["Simulation financière","beige","Finance","10 Nov"],["Attestation KYC","green","KYC","08 Nov"],["NDA signé","silver","Légal","07 Nov"],["Reçu versement #1","green","Reçu","08 Nov"]].map(([n,c,t,d])=>(<tr key={n}><td style={{fontWeight:n.includes("✍")?600:400,color:n.includes("✍")?T.gold:T.brown}}>{n}</td><td><Tag c={c}>{t}</Tag></td><td>{d}</td><td><Btn v="ghost" sz="sm"><I.Download/></Btn></td></tr>))}</tbody></table></Card></div>;
    if(view==="kyc") return <div><Ks items={[["KYC","Vérifié ✓","","up",I.Shield],["Validé","08 Nov","2024","",I.Calendar],["Réf.","KP-0847","","",I.Key],["Renouvellement","Nov 2025","12 mois","up",I.Check]]} cols={4}/><Card title="Mon profil KYC"><div style={{padding:"1.5rem"}}>{[["Nom complet","Jean Kouassi"],["Nationalité","Ivoirienne"],["Profession","Directeur Général"],["Capacité investissement","200M–400M FCFA"],["Statut PPE","Non"]].map(([l,v])=>(<div key={l} style={{display:"flex",justifyContent:"space-between",padding:".7rem 0",borderBottom:`1px solid ${T.lineL}`}}><span style={{fontSize:".56rem",color:T.brown3}}>{l}</span><span style={{fontSize:".62rem",color:T.brown,fontWeight:500}}>{v}</span></div>))}</div></Card></div>;
    if(view==="parrainage") return <Card title="Programme de parrainage"><div style={{padding:"2rem 1.5rem",textAlign:"center"}}><div style={{fontFamily:"'Cormorant Garamond',serif",fontSize:"1.5rem",color:T.brown,marginBottom:"1rem"}}>Votre code de parrainage</div><div style={{fontFamily:"'Cormorant Garamond',serif",fontSize:"2rem",color:T.gold,letterSpacing:".2em",marginBottom:"1.5rem",background:T.goldL,padding:"1.5rem",border:`1px solid rgba(138,106,56,.2)`}}>KP-JK-0847</div><p style={{fontSize:".6rem",color:T.brown3,lineHeight:1.9,marginBottom:"1.5rem"}}>Partagez ce code à vos proches. Dès qu'ils rejoignent K Properties, vous bénéficiez tous les deux d'avantages exclusifs.</p><Btn full>Copier le code</Btn></div></Card>;
    if(view==="notifications") return <Card title="Notifications" actions={<Btn v="ghost" sz="sm">Tout lire</Btn>}>{[[1,"Action requise","Contrat Cocody Heights prêt à signer.","2h","red"],[1,"RDV confirmé","Signature notariale 20 novembre 14h30.","5h","gold"],[1,"Message","Votre conseiller vous a envoyé un message.","Hier","blue"],[0,"Chantier mis à jour","8 nouvelles photos — Avancement 73%.","15 Nov","silver"],[0,"KYC validé","Bienvenue sur K Properties.","08 Nov","green"]].map(([u,t,tx,ti,c])=>(<div key={t} style={{display:"flex",gap:".9rem",padding:"1rem 1.5rem",borderBottom:`1px solid ${T.lineL}`,borderLeft:u?`2px solid ${T.gold}`:"2px solid transparent"}}><div style={{width:6,height:6,borderRadius:"50%",background:u?T.gold:"transparent",border:u?"none":`1px solid ${T.line}`,flexShrink:0,marginTop:5}}/><div style={{flex:1}}><div style={{fontSize:".62rem",fontWeight:500,color:T.brown,marginBottom:".2rem"}}>{t}</div><div style={{fontSize:".58rem",color:T.brown2,lineHeight:1.8}}>{tx}</div></div><div style={{fontSize:".5rem",color:T.brown3,whiteSpace:"nowrap",flexShrink:0}}>{ti}</div></div>))}</Card>;
    if(view==="settings") return <Card title="Paramètres du profil"><div style={{padding:"2rem 1.5rem"}}><div style={{display:"grid",gridTemplateColumns:isMobile?"1fr":"1fr 1fr",gap:"1.5rem",marginBottom:"1.5rem"}}><div><label>Prénom</label><input defaultValue="Jean"/></div><div><label>Nom</label><input defaultValue="Kouassi"/></div></div><div style={{marginBottom:"1.5rem"}}><label>Email</label><input defaultValue="j.kouassi@email.com"/></div><div style={{marginBottom:"2rem"}}><label>Téléphone</label><input defaultValue="+225 07 00 00 00 00"/></div><div style={{display:"flex",gap:".8rem"}}><Btn>Enregistrer</Btn><Btn v="outline">Changer mot de passe</Btn></div></div></Card>;
  }

  // PARTNER
  if(role==="partner"){
    if(view==="overview") return <div><Alert icon={I.Star} type="gold">Félicitations ! <strong>Partenaire Gold ✦</strong> — accès prioritaire aux nouveaux projets.</Alert><Ks items={[["Clients actifs","14","+3 ce mois","up",I.Users],["Volume","1.2Md","FCFA","",I.Money],["Commissions","8.4M","FCFA ce mois","warn",I.Chart],["Statut","Gold ✦","","up",I.Star]]} cols={4}/><div style={{display:"grid",gridTemplateColumns:isMobile?"1fr":"2fr 1fr",gap:1,marginBottom:"1rem"}}><Card title="Mes clients" actions={<Btn v="ghost" sz="sm" onClick={()=>setView("crm")}>CRM →</Btn>}><table><thead><tr><th>Client</th><th>Projet</th><th>Montant</th><th>Étape</th></tr></thead><tbody>{[["Ama Boni","Cocody Heights","120M FCFA","blue","Signature"],["Kofi Diabaté","K Tower","250M FCFA","gold","Négociation"],["Marie Ouédraogo","Bingerville","200M FCFA","silver","KYC"],["Seydou Assoumou","Cocody Heights","85M FCFA","green","Signé ✓"]].map(([n,p,a,c,s])=>(<tr key={n}><td style={{fontWeight:500,color:T.brown}}>{n}</td><td>{p}</td><td style={{color:T.gold,fontWeight:500}}>{a}</td><td><Tag c={c}>{s}</Tag></td></tr>))}</tbody></table></Card><Card title="Performance"><div style={{padding:"1.2rem 1.5rem"}}><BarChart/></div></Card></div></div>;
    if(view==="crm") return <div><Ks items={[["Clients","14","+3","up",I.Users],["KYC","3","En attente","warn",I.Shield],["Signés","2","Ce mois","up",I.Check],["Conversion","68%","","up",I.Trend]]} cols={4}/><Card title="Portefeuille clients" actions={<><Btn v="outline" sz="sm">Filtrer</Btn><Btn sz="sm"><I.Plus/> Ajouter</Btn></>}><table><thead><tr><th>Client</th><th>Projet</th><th>Montant</th><th>Commission</th></tr></thead><tbody>{[["Ama Boni","Cocody Heights","120M FCFA","3.6M FCFA"],["Kofi Diabaté","K Tower","250M FCFA","7.5M FCFA"],["Marie Ouédraogo","Bingerville","200M FCFA","—"],["Seydou Assoumou","Cocody Heights","85M FCFA","2.55M FCFA"]].map(([n,p,a,c])=>(<tr key={n}><td style={{color:T.brown,fontWeight:500}}>{n}</td><td>{p}</td><td>{a}</td><td style={{color:c==="—"?T.brown3:T.green,fontWeight:500}}>{c}</td></tr>))}</tbody></table></Card></div>;
    if(view==="commissions") return <div><Ks items={[["Total cumulé","38.4M","FCFA","up",I.Money],["Ce mois","8.4M","FCFA","up",I.Trend],["En attente","11.1M","FCFA","warn",I.Warning],["Virement","30 Nov","","",I.Calendar]]} cols={4}/><Card title="Historique commissions"><table><thead><tr><th>Date</th><th>Client</th><th>Commission</th><th>Statut</th></tr></thead><tbody>{[["08 Nov","Seydou Assoumou","2.55M FCFA","green","Versée"],["20 Nov","Ama Boni","3.6M FCFA","gold","En attente"],["En cours","Kofi Diabaté","7.5M FCFA","silver","Négociation"]].map(([d,n,c,col,s])=>(<tr key={n}><td>{d}</td><td style={{fontWeight:500,color:T.brown}}>{n}</td><td style={{color:col==="green"?T.green:col==="gold"?T.gold:T.brown3,fontWeight:500}}>{c}</td><td><Tag c={col}>{s}</Tag></td></tr>))}</tbody></table></Card></div>;
    if(view==="catalogue") return <div><Alert icon={I.Star} type="gold">Accès prioritaire Gold — 7 jours avant ouverture publique.</Alert>{[["Résidence Cocody Heights","85M–150M FCFA","En cours","green"],["K Tower — Le Plateau","120M–250M FCFA","Disponible","blue"],["Jardins de Bingerville","200M–400M FCFA","Pré-vente","gold"],["Riviera Palms Estate","Sur dossier","Nouveau ✦","silver"]].map(([n,p,st,c])=>(<div key={n} style={{background:T.ivory,padding:"1.5rem",marginBottom:1,display:"flex",justifyContent:"space-between",alignItems:"center",flexWrap:"wrap",gap:"1rem"}}><div><div style={{fontFamily:"'Cormorant Garamond',serif",fontSize:"1.05rem",color:T.brown,marginBottom:".3rem"}}>{n}</div><div style={{display:"flex",gap:".5rem",alignItems:"center"}}><Tag c={c}>{st}</Tag><span style={{fontSize:".6rem",color:T.gold,fontWeight:500}}>{p}</span></div></div><div style={{display:"flex",gap:".5rem"}}><Btn v="outline" sz="sm"><I.Download/></Btn><Btn sz="sm">Présenter</Btn></div></div>))}</div>;
    if(view==="outils") return <div style={{display:"grid",gridTemplateColumns:isMobile?"1fr":"repeat(2,1fr)",gap:1}}>{[["Générateur de proposition","Proposition PDF personnalisée pour un client.",I.Doc],["Calculateur financement","Simulez mensualités et coût total en direct.",I.Chart],["Kit réseaux sociaux","Visuels Instagram & LinkedIn prêts à publier.",I.Globe],["Fiches techniques projets","Plans, surfaces, équipements par projet.",I.Building],["Visites virtuelles 3D","Présentations immersives à distance.",I.Eye],["Scripts de vente","Argumentaires et réponses aux objections.",I.Book]].map(([t,d,Icon])=>(<div key={t} style={{background:T.ivory,padding:"1.5rem"}}><div style={{color:T.gold,marginBottom:".8rem"}}><Icon/></div><div style={{fontFamily:"'Cormorant Garamond',serif",fontSize:"1rem",color:T.brown,marginBottom:".4rem"}}>{t}</div><div style={{fontSize:".56rem",color:T.brown3,lineHeight:1.7,marginBottom:"1.2rem"}}>{d}</div><Btn sz="sm">Accéder</Btn></div>))}</div>;
    if(view==="stats") return <div><Ks items={[["Ventes","9","Ce trimestre","up",I.Check],["Volume","1.28Md","FCFA","up",I.Money],["Commissions","38.4M","FCFA","up",I.Trend],["Classement","#1","Top performer","up",I.Star]]} cols={4}/><Card title="Évolution ventes — 12 mois"><div style={{padding:"1.2rem 1.5rem"}}><BarChart/></div></Card></div>;
    if(view==="vip") return <div><div style={{background:T.brown,padding:"2rem 1.5rem",marginBottom:1,textAlign:"center"}}><div style={{fontFamily:"'Cormorant Garamond',serif",fontSize:"2rem",color:"#C8952A",marginBottom:".5rem"}}>✦ Statut Gold</div><div style={{fontSize:".62rem",color:"rgba(245,240,232,.6)"}}>9 ventes validées · Niveau maximum atteint</div></div><Card title="Avantages Gold"><div style={{padding:"1.2rem 1.5rem"}}>{["Catalogue projets complet","Générateur de propositions","Accès prioritaire nouveaux projets","Formation avancée","Invitation événements VIP","Bonus sur projets premium","Pré-lancement exclusif","Conseiller dédié K Properties"].map(a=>(<div key={a} style={{display:"flex",alignItems:"center",gap:".8rem",padding:".7rem 0",borderBottom:`1px solid ${T.lineL}`}}><span style={{color:T.gold}}><I.Check/></span><span style={{fontSize:".62rem",color:T.brown}}>{a}</span></div>))}</div></Card></div>;
    if(view==="formation") return <Card title="Parcours certification K Properties">{[["done","Introduction à K Properties","45 min","Complété","100%"],["done","Portfolio projets","60 min","Complété","92%"],["done","Processus KYC & Compliance","30 min","Complété","95%"],["active","Bingerville & Marcory","50 min","En cours","60%"],["pending","Riviera Palms Estate","45 min","18 Déc","0%"]].map(([st,t,dur,stLabel,prog])=>(<div key={t} style={{padding:"1.2rem 1.5rem",borderBottom:`1px solid ${T.lineL}`,display:"flex",gap:"1rem",alignItems:"flex-start"}}><div style={{width:28,height:28,border:`1px solid ${st==="done"?T.gold:st==="active"?T.gold:T.lineL}`,background:st==="done"?T.gold:st==="active"?T.goldL:"transparent",display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0,color:st==="done"?T.ivory:T.gold}}>{st==="done"&&<I.Check/>}{st==="active"&&<span style={{fontSize:".5rem",fontWeight:600}}>→</span>}</div><div style={{flex:1}}><div style={{fontSize:".63rem",fontWeight:500,color:T.brown,marginBottom:".2rem"}}>{t}</div><div style={{fontSize:".55rem",color:T.brown3,marginBottom:".5rem"}}>{dur}</div><div style={{display:"flex",justifyContent:"space-between",flexWrap:"wrap",gap:".5rem"}}><Tag c={st==="done"?"green":st==="active"?"gold":"silver"}>{stLabel}</Tag>{st==="active"&&<Btn sz="sm">Continuer</Btn>}{st==="done"&&<span style={{fontSize:".52rem",color:T.green}}>{prog}</span>}</div></div></div>))}</Card>;
    if(view==="messagerie") return <Card><div style={{display:"flex",flexDirection:isMobile?"column":"row",height:isMobile?"auto":400}}><div style={{width:isMobile?"100%":220,borderRight:isMobile?"none":`1px solid ${T.lineL}`,borderBottom:isMobile?`1px solid ${T.lineL}`:"none"}}>{[["K Properties","Riviera Palms disponible","2h",true],["Admin K Properties","Commission 2.55M virée","Hier",false]].map(([n,p,t,u],i)=>(<div key={i} style={{padding:"1rem 1.2rem",borderBottom:`1px solid ${T.lineL}`,cursor:"pointer",background:i===0?T.goldL:"transparent",borderLeft:u?`2px solid ${T.gold}`:"2px solid transparent"}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:".2rem"}}><span style={{fontSize:".6rem",fontWeight:500,color:T.brown}}>{n}</span><span style={{fontSize:".48rem",color:T.brown3}}>{t}</span></div><div style={{fontSize:".55rem",color:T.brown3,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{p}</div></div>))}</div><div style={{flex:1,display:"flex",flexDirection:"column",minHeight:isMobile?280:0}}><div style={{padding:".9rem 1.5rem",borderBottom:`1px solid ${T.lineL}`}}><div style={{fontSize:".63rem",fontWeight:500,color:T.brown}}>K Properties</div><div style={{fontSize:".52rem",color:T.brown3}}>Équipe commerciale</div></div><div style={{flex:1,padding:"1.2rem",overflowY:"auto",display:"flex",flexDirection:"column",gap:".8rem",background:T.ivory}}>{[["in","Riviera Palms disponible en pré-vente partenaires. Accès prioritaire 7 jours."],["out","Merci, pouvez-vous m'envoyer la brochure ?"],["in","Disponible dans votre Catalogue. Formation dédiée le 18 décembre."]].map(([d,t],i)=>(<div key={i} style={{maxWidth:"78%",padding:".85rem 1rem",fontSize:".62rem",lineHeight:1.8,alignSelf:d==="out"?"flex-end":"flex-start",background:d==="in"?T.cream2:T.brown,color:d==="in"?T.brown:T.cream}}>{t}</div>))}</div><div style={{padding:".9rem 1.5rem",borderTop:`1px solid ${T.lineL}`,display:"flex",gap:".7rem",background:T.ivory}}><input placeholder="Écrire..." style={{flex:1}}/><Btn sz="sm">Envoyer</Btn></div></div></div></Card>;
    if(view==="agenda") return <div><Alert icon={I.Calendar} type="gold">Formation K Properties — 18 décembre. Inscription obligatoire partenaires Gold.</Alert><Card title="Agenda" actions={<Btn sz="sm"><I.Plus/> RDV</Btn>}><TL items={[["active","Signature — Ama Boni","Cabinet Adou, Plateau","Aujourd'hui · 14h30"],["pending","Présentation — Kofi Diabaté","Zoom · K Tower","Demain · 10h00"],["pending","Formation K Properties","Siège · Obligatoire","18 Déc · 10h00"]]}/></Card></div>;
    if(view==="profil") return <div><Ks items={[["Accréditation","Active","Valide","up",I.Shield],["Type","Notaire","K Properties","",I.Scale],["Agrément","Valide","Déc 2026","up",I.Check],["VIP","Gold ✦","","up",I.Star]]} cols={4}/><Card title="Mon profil partenaire"><div style={{padding:"1.5rem"}}><div style={{display:"flex",gap:"1.5rem",alignItems:"flex-start",marginBottom:"2rem",flexWrap:"wrap"}}><div style={{width:60,height:60,background:T.brown,display:"flex",alignItems:"center",justifyContent:"center",fontFamily:"'Cormorant Garamond',serif",fontSize:"1.5rem",color:T.cream,flexShrink:0}}>CA</div><div><div style={{fontFamily:"'Cormorant Garamond',serif",fontSize:"1.3rem",color:T.brown,marginBottom:".3rem"}}>Me Camille Adou</div><div style={{fontSize:".58rem",color:T.gold,marginBottom:".5rem"}}>Notaire · Partenaire Gold ✦</div><div style={{display:"flex",gap:".5rem"}}><Tag c="gold">✦ Gold</Tag><Tag c="green">Accrédité</Tag></div></div></div>{[["Structure","Cabinet Adou & Associés"],["Téléphone","+225 27 00 00 00 00"],["Email","c.adou@cabinet-adou.ci"]].map(([l,v])=>(<div key={l} style={{display:"flex",justifyContent:"space-between",padding:".7rem 0",borderBottom:`1px solid ${T.lineL}`}}><span style={{fontSize:".56rem",color:T.brown3}}>{l}</span><span style={{fontSize:".62rem",color:T.brown,fontWeight:500}}>{v}</span></div>))}</div></Card></div>;
    if(view==="settings") return <Card title="Paramètres"><div style={{padding:"2rem 1.5rem"}}><div style={{display:"grid",gridTemplateColumns:isMobile?"1fr":"1fr 1fr",gap:"1.5rem",marginBottom:"1.5rem"}}><div><label>Prénom</label><input defaultValue="Camille"/></div><div><label>Nom</label><input defaultValue="Adou"/></div></div><div style={{marginBottom:"1.5rem"}}><label>Email</label><input defaultValue="c.adou@cabinet-adou.ci"/></div><div style={{marginBottom:"2rem"}}><label>Téléphone</label><input defaultValue="+225 27 00 00 00 00"/></div><Btn>Enregistrer</Btn></div></Card>;
  }

  // ADMIN
  if(role==="admin"){
    if(view==="overview") return <div><Ks items={[["Membres actifs","148","+12 ce mois","up",I.Users],["KYC en attente","12","À traiter","warn",I.Shield],["CA encaissé","4.2Md","FCFA","up",I.Money],["CA pipeline","18Md","FCFA","",I.Chart]]} cols={4}/><Ks items={[["Projets actifs","5","174 unités","",I.Building],["Partenaires","24","Vérifiés","up",I.Handshake],["Leads","8","Non traités","warn",I.Inbox],["RDV","6","À confirmer","warn",I.Calendar]]} cols={4}/><div style={{display:"grid",gridTemplateColumns:isMobile?"1fr":"2fr 1fr",gap:1,marginBottom:"1rem"}}><Card title="Candidatures KYC — 12 mois"><div style={{padding:"1.2rem 1.5rem"}}><BarChart/></div></Card><Card title="Répartition membres"><div style={{padding:"1.2rem 1.5rem"}}>{[["Acquéreurs",T.gold,102],["Notaires",T.blue,18],["Cabinets",T.green,16],["Agences",T.brown3,12]].map(([l,c,v])=>(<div key={l} style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:".6rem 0",borderBottom:`1px solid ${T.lineL}`}}><div style={{display:"flex",alignItems:"center",gap:".6rem",fontSize:".58rem",color:T.brown2}}><div style={{width:7,height:7,borderRadius:"50%",background:c}}/>{l}</div><div style={{fontSize:".65rem",color:T.brown,fontWeight:500}}>{v}</div></div>))}</div></Card></div></div>;
    if(view==="alertes") return <div><Ks items={[["Urgentes","3","Immédiate","red",I.Warning],["Importantes","4","24h","warn",I.Bell],["Infos","5","À traiter","",I.Eye],["Résolues","23","Ce mois","up",I.Check]]} cols={4}/>{[["red","KYC dépassé — 7 jours","Marie Ouédraogo — Dossier non traité depuis 7 jours.","Urgent"],["red","KYC dépassé — 6 jours","Ibrahim Konaté — Dossier non traité depuis 6 jours.","Urgent"],["red","Agrément expirant","Cabinet Diallo — Agrément expire dans 15 jours.","Urgent"],["orange","Contrat non signé","Jean Kouassi — Contrat en attente depuis 3 jours.","Attention"],["orange","Document illisible","Fatoumata Coulibaly — Pièce d'identité illisible.","Attention"]].map(([tc,t,d,sev])=>(<div key={t} style={{background:T.ivory,padding:"1.2rem 1.5rem",marginBottom:1,display:"flex",justifyContent:"space-between",alignItems:"center",flexWrap:"wrap",gap:".8rem"}}><div style={{display:"flex",alignItems:"flex-start",gap:"1rem",flex:1}}><span style={{color:tc==="red"?T.red:T.orange,flexShrink:0,marginTop:1}}><I.Warning/></span><div><div style={{fontSize:".62rem",fontWeight:500,color:T.brown,marginBottom:".25rem"}}>{t}</div><div style={{fontSize:".56rem",color:T.brown3,lineHeight:1.7}}>{d}</div></div></div><div style={{display:"flex",gap:".6rem"}}><Tag c={tc}>{sev}</Tag><Btn sz="sm">Traiter</Btn></div></div>))}</div>;
    if(view==="kyc") return <div><Ks items={[["En attente","12","À traiter","warn",I.Shield],["Incomplets","4","Docs manquants","warn",I.Warning],["Validés","34","+18%","up",I.Check],["Délai moy.","3.8j","Objectif 5j","up",I.Calendar]]} cols={4}/><Card title="File de traitement KYC" actions={<><Btn v="outline" sz="sm">Filtrer</Btn><Btn sz="sm"><I.Download/> Export</Btn></>}>{[["Marie Ouédraogo","Acquéreur","Burkina Faso","200M FCFA","14 Nov","Moyen"],["Cabinet Diallo","Partenaire","Côte d'Ivoire","—","13 Nov","Faible"],["Ibrahim Konaté","Acquéreur","Mali","300M FCFA","12 Nov","Moyen"],["Fatoumata Coulibaly","Acquéreur","Guinée","250M FCFA","10 Nov","Élevé"]].map(([n,t,loc,amt,date,risk])=>(<div key={n} style={{borderBottom:`1px solid ${T.lineL}`,padding:"1.2rem 1.5rem"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",flexWrap:"wrap",gap:".8rem"}}><div><div style={{fontSize:".63rem",fontWeight:500,color:T.brown,marginBottom:".2rem"}}>{n} <span style={{fontWeight:400,color:T.brown3}}>· {t} · {loc} · {date}</span></div><div style={{display:"flex",gap:".5rem"}}><Tag c="beige">{amt}</Tag><Tag c={risk==="Élevé"?"red":risk==="Moyen"?"orange":"green"}>Risque {risk}</Tag></div></div><div style={{display:"flex",gap:".5rem"}}><Btn v="outline" sz="sm"><I.Eye/></Btn><Btn style={{background:T.red,color:T.cream,border:`1px solid ${T.red}`,fontSize:".5rem",padding:".5rem .9rem",letterSpacing:".1em"}} sz="sm">Rejeter</Btn><Btn style={{background:T.green,color:T.ivory,border:`1px solid ${T.green}`,fontSize:".5rem",padding:".5rem .9rem",letterSpacing:".1em"}} sz="sm"><I.Check/> Valider</Btn></div></div></div>))}</Card></div>;
    if(view==="membres") return <div><Ks items={[["Total","148","","",I.Users],["Acquéreurs","102","69%","",I.Person],["Partenaires","46","31%","",I.Handshake],["Nouveaux","12","Ce mois","up",I.Plus]]} cols={4}/><Card title="Tous les membres" actions={<><Btn v="outline" sz="sm"><I.Download/></Btn><Btn sz="sm"><I.Plus/> Inviter</Btn></>}><table><thead><tr><th>Membre</th><th>Type</th><th>KYC</th><th>VIP</th><th>Statut</th></tr></thead><tbody>{[["JK","Jean Kouassi","Acquéreur","beige","green","Vérifié","—","Actif",T.green],["CA","Me Camille Adou","Notaire","gold","green","Vérifié","✦ Gold","Actif",T.green],["PI","Prestige Immo CI","Agence","beige","green","Vérifié","Silver","Actif",T.green],["MO","Marie Ouédraogo","Acquéreur","beige","gold","En cours","—","En attente",T.gold]].map(([ini,n,type,tc,kc,ks,vip,status,sc])=>(<tr key={n}><td><div style={{display:"flex",alignItems:"center",gap:".6rem"}}><div style={{width:26,height:26,background:T.cream2,border:`1px solid ${T.line}`,display:"flex",alignItems:"center",justifyContent:"center",fontFamily:"'Cormorant Garamond',serif",fontSize:".85rem",color:T.brown}}>{ini}</div><span style={{color:T.brown}}>{n}</span></div></td><td><Tag c={tc}>{type}</Tag></td><td><Tag c={kc}>{ks}</Tag></td><td style={{color:T.gold}}>{vip}</td><td style={{color:sc,fontWeight:500}}>{status}</td></tr>))}</tbody></table></Card></div>;
    if(view==="leads") return <div><Ks items={[["Leads","8","Non traités","warn",I.Inbox],["Chauds","3","","red",I.Warning],["Tièdes","3","","warn",I.Bell],["Froids","2","","",I.Eye]]} cols={4}/><Card title="Leads entrants" actions={<Btn sz="sm"><I.Plus/> Ajouter</Btn>}>{[["Kofi Mensah","Ghana","Reçu 72h","Chaud 🔥","red"],["Aminata Traoré","Sénégal","Reçu 48h","Chaud 🔥","red"],["Paul Bamba","Côte d'Ivoire","Reçu 24h","Tiède","orange"],["Sarah Kone","France","Reçu 2j","Tiède","orange"]].map(([n,pays,date,score,c])=>(<div key={n} style={{padding:"1.2rem 1.5rem",borderBottom:`1px solid ${T.lineL}`,display:"flex",justifyContent:"space-between",alignItems:"center",flexWrap:"wrap",gap:".8rem"}}><div><div style={{display:"flex",alignItems:"center",gap:".8rem",marginBottom:".3rem"}}><span style={{fontSize:".63rem",fontWeight:500,color:T.brown}}>{n}</span><Tag c={c}>{score}</Tag></div><div style={{fontSize:".54rem",color:T.brown3}}>{pays} · {date}</div></div><div style={{display:"flex",gap:".5rem"}}><Btn v="outline" sz="sm">Contacter</Btn><Btn sz="sm">Assigner</Btn></div></div>))}</Card></div>;
    if(view==="projets") return <div><Ks items={[["Actifs","5","174 unités","",I.Building],["Vendues","94","54%","up",I.Check],["Disponibles","80","46%","",I.Eye],["CA projeté","18Md","FCFA","",I.Money]]} cols={4}/>{[["Résidence Cocody Heights","Résidentiel","48","35","73%","En cours","green"],["K Tower — Le Plateau","Bureaux","32","18","55%","Disponible","blue"],["Jardins de Bingerville","Villas","40","11","28%","Pré-vente","gold"],["Marcory Premium Center","Mixte","24","2","8%","Lancement","orange"],["Riviera Palms Estate","Résidentiel","30","0","0%","Pipeline","silver"]].map(([n,type,total,sold,pct,status,c])=>(<div key={n} style={{background:T.ivory,padding:"1.5rem",marginBottom:1}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",flexWrap:"wrap",gap:"1rem",marginBottom:"1rem"}}><div><div style={{fontFamily:"'Cormorant Garamond',serif",fontSize:"1.05rem",color:T.brown,marginBottom:".3rem"}}>{n}</div><div style={{display:"flex",gap:".5rem"}}><Tag c="beige">{type}</Tag><Tag c={c}>{status}</Tag></div></div><div style={{display:"flex",gap:".5rem"}}><Btn v="outline" sz="sm">Modifier</Btn><Btn sz="sm">Gérer</Btn></div></div><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:"1rem",marginBottom:".8rem"}}>{[["Total",total],["Vendues",sold],["Restantes",parseInt(total)-parseInt(sold)],["Avancement",pct]].map(([l,v])=>(<div key={l}><div style={{fontSize:".44rem",letterSpacing:".12em",textTransform:"uppercase",color:T.brown3,marginBottom:".3rem"}}>{l}</div><div style={{fontSize:".72rem",fontWeight:500,color:T.brown}}>{v}</div></div>))}</div><div style={{height:2,background:T.lineL}}><div style={{width:pct,height:"100%",background:T.gold}}/></div></div>))}</div>;
    if(view==="finance") return <div><Ks items={[["CA projeté","18Md","FCFA","",I.Chart],["Encaissé","4.2Md","FCFA","up",I.Money],["Pipeline","13.8Md","Promesses","",I.Trend],["Taux","23%","vs projeté","",I.Eye]]} cols={4}/><Card title="Encaissements — 12 mois"><div style={{padding:"1.2rem 1.5rem"}}><BarChart/></div></Card><Card title="Performance par projet"><table><thead><tr><th>Projet</th><th>CA Projeté</th><th>Encaissé</th><th>Taux</th></tr></thead><tbody>{[["Cocody Heights","4.08Md","2.98Md","73%",T.green],["K Tower","3.84Md","2.11Md","55%",T.gold],["Bingerville","8Md","2.24Md","28%",T.orange],["Marcory","2.4Md","0.19Md","8%",T.red]].map(([n,p,e,t,c])=>(<tr key={n}><td style={{fontWeight:500,color:T.brown}}>{n}</td><td>{p}</td><td style={{color:T.green,fontWeight:500}}>{e}</td><td style={{color:c,fontWeight:500}}>{t}</td></tr>))}</tbody></table></Card></div>;
    if(view==="commissions") return <div><Ks items={[["Versé","94M","FCFA","up",I.Money],["En attente","28M","FCFA","warn",I.Warning],["Ce mois","8.4M","FCFA","up",I.Trend],["Virement","30 Nov","","",I.Calendar]]} cols={4}/><Card title="Commissions par partenaire" actions={<Btn sz="sm">Tout verser</Btn>}><table><thead><tr><th>Partenaire</th><th>Type</th><th>Commission</th><th>Statut</th></tr></thead><tbody>{[["Me Camille Adou","Notaire","38.4M FCFA","green","Versée"],["Prestige Immo CI","Agence","25.6M FCFA","gold","En attente"],["Cabinet Patrimoine+","Cabinet","17M FCFA","gold","En attente"]].map(([n,t,c,col,s])=>(<tr key={n}><td style={{fontWeight:500,color:T.brown}}>{n}</td><td><Tag c="beige">{t}</Tag></td><td style={{color:col==="green"?T.green:T.gold,fontWeight:500}}>{c}</td><td><Tag c={col}>{s}</Tag></td></tr>))}</tbody></table></Card></div>;
    if(view==="crm") return <div><Ks items={[["Pipeline","22","Dossiers actifs","",I.Chart],["Valeur","3.2Md","FCFA","up",I.Money],["Closing","6","Ce mois","up",I.Check],["Conversion","31%","KYC → Acte","up",I.Trend]]} cols={4}/><div style={{display:"grid",gridTemplateColumns:isMobile?"1fr":"repeat(5,1fr)",gap:1}}>{[["Prospect",["Kofi Mensah","Chen Wei"],"silver"],["KYC",["Marie Ouédraogo","Ibrahim"],"gold"],["Négociation",["Ama Boni","Kofi D."],"blue"],["Signature",["Jean Kouassi","Seydou"],"orange"],["Signé ✓",["Seydou A.","Mme Coulibaly"],"green"]].map(([stage,cards,c])=>(<div key={stage}><div style={{fontSize:".52rem",letterSpacing:".12em",textTransform:"uppercase",color:T.brown3,marginBottom:".8rem",display:"flex",justifyContent:"space-between"}}><span>{stage}</span><span style={{background:T.cream2,padding:".1rem .5rem"}}>{cards.length}</span></div><div style={{background:T.cream2,padding:".8rem",minHeight:120}}>{cards.map(card=>(<div key={card} style={{background:T.ivory,border:`1px solid ${T.lineL}`,padding:".8rem",marginBottom:".5rem",fontSize:".58rem",fontWeight:500,color:T.brown}}>{card}</div>))}</div></div>))}</div></div>;
    if(view==="messagerie") return <Card><div style={{display:"flex",flexDirection:isMobile?"column":"row",height:isMobile?"auto":480}}><div style={{width:isMobile?"100%":240,borderRight:isMobile?"none":`1px solid ${T.lineL}`,borderBottom:isMobile?`1px solid ${T.lineL}`:"none",overflowY:"auto"}}><div style={{padding:".8rem 1.2rem",borderBottom:`1px solid ${T.lineL}`}}><input placeholder="Rechercher..."/></div>{[["JK","Jean Kouassi","Question échéancier","14h32",true],["CA","Me Adou","Confirmation RDV","Hier",false],["PI","Prestige Immo","Nouveau client","2j",true]].map(([ini,n,p,t,u])=>(<div key={n} style={{padding:".9rem 1.2rem",borderBottom:`1px solid ${T.lineL}`,cursor:"pointer",borderLeft:u?`2px solid ${T.gold}`:"2px solid transparent"}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:".3rem"}}><span style={{fontSize:".6rem",fontWeight:500,color:T.brown}}>{n}</span><span style={{fontSize:".48rem",color:T.brown3}}>{t}</span></div><div style={{fontSize:".55rem",color:T.brown3,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{p}</div></div>))}</div><div style={{flex:1,display:"flex",flexDirection:"column",minHeight:isMobile?320:0}}><div style={{padding:".9rem 1.5rem",borderBottom:`1px solid ${T.lineL}`,display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><div style={{fontSize:".63rem",fontWeight:500,color:T.brown}}>Jean Kouassi</div><div style={{fontSize:".52rem",color:T.brown3}}>Acquéreur · En ligne</div></div><div style={{display:"flex",gap:".5rem"}}><Tag c="red">Urgent</Tag><Btn v="outline" sz="sm">Assigner</Btn></div></div><div style={{flex:1,padding:"1.2rem",overflowY:"auto",display:"flex",flexDirection:"column",gap:".8rem",background:T.ivory}}>{[["in","Question concernant mon échéancier Cocody Heights."],["out","Votre prochain versement de 17M est prévu le 20 novembre."],["in","Est-il possible de décaler d'une semaine ?"],["out","Je transmets au service financier. Réponse sous 24h."]].map(([d,t],i)=>(<div key={i} style={{maxWidth:"75%",padding:".85rem 1rem",fontSize:".62rem",lineHeight:1.8,alignSelf:d==="out"?"flex-end":"flex-start",background:d==="in"?T.cream2:T.brown,color:d==="in"?T.brown:T.cream}}>{t}</div>))}</div><div style={{padding:".9rem 1.5rem",borderTop:`1px solid ${T.lineL}`,display:"flex",gap:".7rem",background:T.ivory}}><select style={{flex:1,fontSize:".58rem",color:T.brown3}}><option>Modèle : KYC validé</option><option>Modèle : RDV confirmé</option><option>Message libre</option></select><Btn sz="sm">Envoyer</Btn></div></div></div></Card>;
    if(view==="agenda") return <div><Ks items={[["Aujourd'hui","3","RDV","",I.Calendar],["Semaine","8","","up",I.Calendar],["À confirmer","6","","warn",I.Warning],["Demandes","4","Nouvelles","warn",I.Bell]]} cols={4}/><Card title="Agenda — Cette semaine" actions={<Btn sz="sm"><I.Plus/> RDV</Btn>}>{[["14h30","Aujourd'hui","Signature — Jean Kouassi","Me Adou, Plateau","Confirmé","green"],["10h00","Demain","Présentation — Kofi Diabaté","Visio Zoom","Confirmé","green"],["15h00","Jeu 21 Nov","Qualification — Aminata Traoré","Appel téléphonique","À confirmer","gold"]].map(([h,d,t,det,st,c])=>(<div key={t} style={{padding:"1.1rem 1.5rem",borderBottom:`1px solid ${T.lineL}`,display:"flex",gap:"1rem",alignItems:"flex-start"}}><div style={{flexShrink:0,width:55}}><div style={{fontSize:".62rem",fontWeight:500,color:T.brown}}>{h}</div><div style={{fontSize:".52rem",color:T.brown3}}>{d}</div></div><div style={{flex:1}}><div style={{fontSize:".63rem",fontWeight:500,color:T.brown,marginBottom:".25rem"}}>{t}</div><div style={{fontSize:".54rem",color:T.brown3}}>{det}</div></div><div style={{display:"flex",gap:".5rem",alignItems:"center"}}><Tag c={c}>{st}</Tag>{st==="À confirmer"&&<Btn sz="sm"><I.Check/></Btn>}</div></div>))}</Card></div>;
    if(view==="partenaires") return <div><Ks items={[["Actifs","24","Vérifiés","up",I.Handshake],["Notaires","8","","",I.Scale],["Cabinets","7","","",I.Doc],["Agences","9","","",I.Building]]} cols={4}/><Card title="Réseau partenaires" actions={<><Btn v="outline" sz="sm"><I.Download/></Btn><Btn sz="sm"><I.Plus/> Inviter</Btn></>}><table><thead><tr><th>Partenaire</th><th>Type</th><th>VIP</th><th>Ventes</th><th>Agrément</th></tr></thead><tbody>{[["Me Camille Adou","Notaire","✦ Gold","9","Valide","green"],["Prestige Immo CI","Agence","Silver","6","⚠ Exp.","red"],["Cabinet Patrimoine+","Cabinet","Silver","4","Valide","green"]].map(([n,t,vip,v,agr,c])=>(<tr key={n}><td style={{fontWeight:500,color:T.brown}}>{n}</td><td><Tag c="beige">{t}</Tag></td><td style={{color:T.gold,fontWeight:500}}>{vip}</td><td>{v}</td><td><Tag c={c}>{agr}</Tag></td></tr>))}</tbody></table></Card></div>;
    if(view==="exports") return <div style={{display:"flex",flexDirection:"column",gap:1}}>{[["Membres & KYC","Liste complète, statuts, dates"],["Ventes & Projets","Dashboard commercial, taux"],["Reporting financier","CA, encaissements, pipeline"],["Commissions partenaires","Détail par partenaire"]].map(([t,d])=>(<div key={t} style={{background:T.ivory,padding:"1.3rem 1.5rem",display:"flex",justifyContent:"space-between",alignItems:"center",flexWrap:"wrap",gap:".8rem"}}><div><div style={{fontSize:".63rem",fontWeight:500,color:T.brown,marginBottom:".3rem"}}>{t}</div><div style={{fontSize:".56rem",color:T.brown3}}>{d}</div></div><div style={{display:"flex",gap:".5rem"}}><Btn v="outline" sz="sm"><I.Download/> Excel</Btn><Btn sz="sm"><I.Download/> PDF</Btn></div></div>))}</div>;
    if(view==="settings") return <Card title="Paramètres & Rôles"><div style={{padding:"2rem 1.5rem"}}><div style={{display:"grid",gridTemplateColumns:isMobile?"1fr":"1fr 1fr",gap:"1.5rem",marginBottom:"1.5rem"}}><div><label>Prénom</label><input defaultValue="Admin"/></div><div><label>Nom</label><input defaultValue="K Properties"/></div></div><div style={{marginBottom:"1.5rem"}}><label>Email</label><input defaultValue="admin@kproperties.ci"/></div><div style={{marginBottom:"2rem"}}><label>Société</label><input defaultValue="K Properties · AFRIGROUPE"/></div><Btn>Enregistrer</Btn></div></Card>;
  }
  return <div style={{padding:"3rem",textAlign:"center",color:T.brown3,fontFamily:"'Cormorant Garamond',serif",fontSize:"1.4rem"}}>Section en cours de développement</div>;
}

function Dashboard({goto,role}){
  const nav=NAVS[role];
  const info=INFO[role];
  const[view,setView]=useState("overview");
  const[open,setOpen]=useState(false);
  const w=useW(),isMobile=w<768;
  const cur=nav.find(i=>i.id===view);
  const SB=()=>(<>
    <div style={{padding:"1.4rem 1.5rem",borderBottom:`1px solid ${T.lineL}`}}><Logo/><div style={{fontSize:".42rem",letterSpacing:".2em",textTransform:"uppercase",color:T.brown3,marginTop:".5rem"}}>{info.label}</div></div>
    <div style={{padding:"1rem 1.5rem",borderBottom:`1px solid ${T.lineL}`,display:"flex",alignItems:"center",gap:".8rem"}}><div style={{width:34,height:34,background:T.brown,display:"flex",alignItems:"center",justifyContent:"center",fontFamily:"'Cormorant Garamond',serif",fontSize:".9rem",color:T.cream,flexShrink:0}}>{info.ini}</div><div><div style={{fontSize:".62rem",fontWeight:500,color:T.brown}}>{info.name}</div><div style={{fontSize:".46rem",letterSpacing:".12em",textTransform:"uppercase",color:T.gold,marginTop:".15rem"}}>{info.role}</div></div></div>
    <nav style={{flex:1,padding:".8rem 0",overflowY:"auto"}}>{nav.map((item,i)=>item.s?(<div key={i} style={{fontSize:".42rem",letterSpacing:".22em",textTransform:"uppercase",color:T.brown3,padding:".3rem 1.5rem",marginTop:".5rem",opacity:.7}}>{item.s}</div>):(<div key={item.id} onClick={()=>{setView(item.id);if(isMobile)setOpen(false);}} style={{display:"flex",alignItems:"center",gap:".7rem",padding:".65rem 1.5rem",fontSize:".6rem",cursor:"pointer",color:view===item.id?T.brown:T.brown3,background:view===item.id?T.goldL:"transparent",borderRight:view===item.id?`2px solid ${T.gold}`:"2px solid transparent"}}><span style={{color:view===item.id?T.gold:T.brown3,flexShrink:0,display:"flex"}}><item.ic/></span><span style={{flex:1}}>{item.lb}</span>{item.b&&<span style={{background:T.gold,color:T.ivory,fontSize:".42rem",padding:".12rem .45rem",fontWeight:600}}>{item.b}</span>}</div>))}</nav>
    <div style={{padding:"1.1rem 1.5rem",borderTop:`1px solid ${T.lineL}`}}><button onClick={()=>goto("landing")} style={{display:"flex",alignItems:"center",gap:".5rem",background:"transparent",border:"none",cursor:"pointer",fontSize:".52rem",color:T.brown3,fontFamily:"'Montserrat',sans-serif",letterSpacing:".12em"}}><I.Key/> Déconnexion</button></div>
  </>);
  return(<div style={{display:"flex",minHeight:"100vh",background:T.cream}}>
    {!isMobile&&<div style={{width:245,background:T.ivory,display:"flex",flexDirection:"column",position:"fixed",top:0,left:0,bottom:0,borderRight:`1px solid ${T.lineL}`,zIndex:100}}><SB/></div>}
    {isMobile&&open&&<div style={{position:"fixed",inset:0,zIndex:200}}><div onClick={()=>setOpen(false)} style={{position:"absolute",inset:0,background:"rgba(26,14,8,.4)"}}/><div style={{position:"absolute",left:0,top:0,bottom:0,width:260,background:T.ivory,display:"flex",flexDirection:"column",borderRight:`1px solid ${T.lineL}`}}><SB/></div></div>}
    <div style={{marginLeft:isMobile?0:245,flex:1,minWidth:0}}>
      <div style={{background:T.ivory,padding:"1rem 1.5rem",display:"flex",justifyContent:"space-between",alignItems:"center",borderBottom:`1px solid ${T.lineL}`,position:"sticky",top:0,zIndex:90}}>
        <div style={{display:"flex",alignItems:"center",gap:"1rem"}}>
          {isMobile&&<div onClick={()=>setOpen(true)} style={{width:30,height:30,border:`1px solid ${T.line}`,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",gap:4,cursor:"pointer",flexShrink:0}}><div style={{width:12,height:"0.5px",background:T.brown}}/><div style={{width:12,height:"0.5px",background:T.brown}}/><div style={{width:12,height:"0.5px",background:T.brown}}/></div>}
          <div style={{display:"flex",alignItems:"center",gap:".5rem"}}>{cur?.ic&&<span style={{color:T.gold,display:"flex"}}><cur.ic/></span>}<div style={{fontFamily:"'Cormorant Garamond',serif",fontSize:isMobile?"1rem":"1.15rem",fontWeight:400,color:T.brown}}>{cur?.lb||"K Properties"}</div></div>
        </div>
        <div style={{display:"flex",alignItems:"center",gap:".6rem"}}>
          <div onClick={()=>setView("notifications"||"alertes")} style={{width:30,height:30,border:`1px solid ${T.line}`,display:"flex",alignItems:"center",justifyContent:"center",cursor:"pointer",color:T.brown3,position:"relative"}}><I.Bell/><div style={{position:"absolute",top:4,right:4,width:5,height:5,background:T.gold,borderRadius:"50%"}}/></div>
          <div onClick={()=>setView("messagerie")} style={{width:30,height:30,border:`1px solid ${T.line}`,display:"flex",alignItems:"center",justifyContent:"center",cursor:"pointer",color:T.brown3,position:"relative"}}><I.Message/><div style={{position:"absolute",top:4,right:4,width:5,height:5,background:T.gold,borderRadius:"50%"}}/></div>
          {!isMobile&&<Btn sz="sm" onClick={()=>goto("landing")}>← Site</Btn>}
        </div>
      </div>
      <div style={{padding:isMobile?"1.2rem":"1.8rem 2rem"}}><DView role={role} view={view} setView={setView}/></div>
    </div>
  </div>);
}

export default function App(){
  const[page,setPage]=useState("landing");
  const[role,setRole]=useState("client");
  const loginAs=r=>{setRole(r);setPage("dashboard");};
  return(<div style={{minHeight:"100vh",background:T.cream,color:T.brown}}><style>{css}</style>{page==="landing"&&<Landing goto={setPage}/>}{page==="auth"&&<Auth goto={setPage} loginAs={loginAs}/>}{page==="kyc"&&<KYC goto={setPage} loginAs={loginAs}/>}{page==="dashboard"&&<Dashboard goto={setPage} role={role}/>}</div>);
}
